'use strict';
/* Demonstrativo financeiro da gestão. Não persiste valores na fila offline. */
function perfComissaoBotaoHTML() {
  return '<p><button type="button" class="btn-ghost" id="perf-comissao">Comissão · demonstrativo e aprovação</button></p><p class="metricas-nota">Produção e ranking são operacionais. Comissão exige entrega comprovada e decisão documentada; prêmio exige revisão própria.</p>';
}
function perfComissaoWire(el) {
  const b=el.querySelector('#perf-comissao');if(b)b.onclick=()=>perfComissaoAbrir().catch(e=>toast(e.message,'error'));
}
const comissaoRotulo=s=>({sem_falha:'Sem falha comprovada',falha_comprovada:'Falha comprovada',abono:'Abono justificado',pendente:'Pendente',previa:'Prévia',aprovacao:'Aprovação',criterios_documentados:'Critérios revisados',elegivel:'Elegível',inelegivel:'Não elegível',interna:'Montagem interna',externa:'Equipe externa',elegibilidade:'Elegibilidade',identidade:'Identidade da equipe',substituicoes:'Substituições',empates:'Empates',premios:'Prêmios',decisao:'Decisão da gestão'})[s]||s;
const comissaoData=s=>s?new Date(s.length===10?s+'T12:00:00':s).toLocaleString('pt-BR',s.length===10?{dateStyle:'short'}:{dateStyle:'short',timeStyle:'short'}):'';
const comissaoDinheiro=c=>c==null?'Pendente':dinheiroCasa(c/100);
function comissaoResumoHTML(r) {
  if(!r)return '<p>Ainda não há revisão financeira neste período.</p>';
  const a=r.apuracao;
  return `<h4>Revisão ${esc(r.revisao)} · ${r.tipo==='aprovacao'?'Aprovada pela gestão':'Prévia para revisão'} · ${a.config.modo==='efetivo'?'Programa efetivo':'Teste — sem exportação para pagamento'}</h4><p>${esc(r.autor?.nome)} · ${esc(comissaoData(r.em))} · ${esc(r.motivo)}</p><p>Comissão apurada: <strong>${comissaoDinheiro(a.totalCentavos)}</strong>${a.pendencias.length?' · total parcial, existem pendências':''}.</p>${a.pendencias.length?`<ul>${a.pendencias.map(p=>`<li>${esc(p)}</li>`).join('')}</ul>`:''}
  <div class="casa-tabela-wrap"><table class="casa-tabela"><thead><tr><th>O.S. / entrega</th><th>Base líquida</th><th>Descontos</th><th>Decisão / pontos do programa</th><th>Comissão</th><th>Interna</th><th>Externa</th></tr></thead><tbody>${a.linhas.map(l=>`<tr><td>${esc(l.numero)} · ${esc(comissaoData(l.dia))}<small class="bloco">${esc(l.entregaId||'Integral')} · ${esc(l.origemValor||'')}</small></td><td>${comissaoDinheiro(l.baseLiquidaCentavos)}</td><td>${l.descontoCentavos==null?'':comissaoDinheiro(l.descontoCentavos)}<small class="bloco">${esc(l.desconto)}</small></td><td>${esc(comissaoRotulo(l.decisao))} · ${l.pontos==null?'pendente':esc(Number(l.pontos.toFixed(4)).toLocaleString('pt-BR'))}<small class="bloco">${l.pendencias.map(esc).join('; ')}</small></td><td>${comissaoDinheiro(l.comissaoCentavos)}</td><td>${comissaoDinheiro(l.internaCentavos)}</td><td>${comissaoDinheiro(l.externaCentavos)}</td></tr>`).join('')}</tbody></table></div>
  <h4>Rateios por pessoa e entrega</h4><ul>${a.linhas.flatMap(l=>l.pagamentos.map(p=>`<li>O.S. ${esc(l.numero)} · ${esc(l.entregaId||l.id)} · ${esc(p.nome||p.pessoaId)} · ${esc(comissaoRotulo(p.tipo))} · ${esc(p.cota/100)}% da parcela · ${comissaoDinheiro(p.centavos)}</li>`)).join('')}</ul><h4>Diferenças para conciliação</h4><p>${a.anteriorAprovacao?'Comparação com a aprovação anterior: ' + esc(a.anteriorAprovacao):'Primeira aprovação: valor integral a conferir.'} Exportar não efetua pagamento.</p><ul>${(a.ajustes||[]).map(p=>`<li>${esc(p.nome||p.pessoaId)} · ${esc(comissaoRotulo(p.tipo))} · diferença ${comissaoDinheiro(p.diferencaCentavos)}</li>`).join('')}</ul><h4>Reconhecimento: ${esc(comissaoRotulo(a.reconhecimento.situacao))}</h4><p>${esc(a.reconhecimento.aviso)}</p><dl>${Object.entries(a.reconhecimento.criterios).filter(([k])=>k!=='avaliacoes').map(([k,v])=>`<dt>${esc(comissaoRotulo(k))}</dt><dd>${esc(v)}</dd>`).join('')}</dl><ul>${(a.reconhecimento.equipes||[]).map(e=>`<li>${esc(e.nome)} · ${e.pendente?'pontos pendentes':esc(Number(e.pontos.toFixed(4)).toLocaleString('pt-BR'))+' O.S. equivalentes elegíveis'} · ${esc(comissaoRotulo(e.situacao))}${e.substituicao?' · houve substituição':''}${e.solo?' · composição solo':''}${e.empate?' · empate':''}<small class="bloco">${esc(e.justificativa)}</small></li>`).join('')}</ul>`;
}
async function perfComissaoAbrir() {
  const fonte=perfFonteAtual();
  if(!fonte?.fechadoEm)return toast('Selecione uma revisão fechada em Base e fechamento para apurar a comissão.','error');
  const periodo=fonte.periodo||{de:fonte.de,ate:fonte.ate};
  const d=perfDialog('Comissão do período', '<p>Consultando revisões financeiras…</p>');
  d.classList.add('comissao-dialog');
  try {
    const resposta=await STORE.api({action:'performanceComissaoListar',...periodo});
    if(!Array.isArray(resposta.revisoes))throw new Error(resposta.error||'Não foi possível consultar as revisões.');
    const revisoes=resposta.revisoes, ultima=revisoes[0];
    d.querySelector('p')?.remove();
    const corpo=d.querySelector('.perf-dialog-corpo')||d.querySelector('section')||d;
    // O diálogo mantém o botão nativo de fechar; conteúdo criado em um filho próprio.
    const conteudo=document.createElement('div');conteudo.innerHTML=`<p>Fechamento operacional · revisão ${esc(fonte.revisao)}. Cada revisão financeira preserva sua configuração, evidências e decisões. Uma aprovação não efetua pagamento.</p><label>Revisão financeira <select id="comissao-versao">${revisoes.map(r=>`<option value="${esc(r.id)}">${r.revisao} · ${esc(comissaoRotulo(r.tipo))} · ${esc(comissaoData(r.em))}</option>`).join('')}</select></label><div id="comissao-resumo">${comissaoResumoHTML(ultima)}</div><p><button type="button" class="btn-primary" id="comissao-nova">Configurar e criar nova prévia</button> <button type="button" class="btn-ghost" id="comissao-aprovar">Revisar e aprovar</button> <button type="button" class="btn-ghost" id="comissao-exportar">Exportar para conferência de pagamento</button></p><p role="alert" id="comissao-erro"></p>`;
    corpo.appendChild(conteudo);
    const sel=conteudo.querySelector('#comissao-versao'),erro=conteudo.querySelector('#comissao-erro');
    const escolhida=()=>revisoes.find(r=>r.id===sel.value)||ultima;
    sel.onchange=()=>{conteudo.querySelector('#comissao-resumo').innerHTML=comissaoResumoHTML(escolhida());};
    conteudo.querySelector('#comissao-nova').onclick=()=>comissaoEditar(fonte,ultima,periodo,d,resposta.pessoas||[]);
    conteudo.querySelector('#comissao-aprovar').onclick=()=>{
      const r=escolhida(),e=COMISSAO.erroAprovacao(r,r?.hash,true);
      if(e||r!==ultima){erro.textContent=e||'Apenas a última prévia pode ser aprovada.';return;}
      const confirmar=perfDialog('Aprovar demonstrativo',`<form><p>Revisão ${r.revisao}: ${comissaoDinheiro(r.apuracao.totalCentavos)}. ${r.apuracao.config.modo==='teste'?'Teste, sem exportação para pagamento.':'Programa efetivo.'} Confira os rateios e as evidências antes de aprovar.</p><label>Justificativa da aprovação <textarea name="motivo" required minlength="5" maxlength="500"></textarea></label><label><input name="confirmacao" type="checkbox" required> Revisei a entrega física, a responsabilidade, os cadastros e os centavos do demonstrativo.</label><button class="btn-primary" type="submit">Confirmar aprovação</button><p role="alert"></p></form>`);
      confirmar.classList.add('comissao-dialog');
      confirmar.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const form=ev.currentTarget,btn=form.querySelector('button');btn.disabled=true;try{const out=await STORE.api({action:'performanceComissaoAprovar',...periodo,anterior:r.id,hash:r.hash,motivo:form.elements.motivo.value,confirmacao:form.elements.confirmacao.checked,requestId:crypto.randomUUID()});if(!out.ok)throw new Error(out.error);confirmar.close();await perfComissaoAbrir();}catch(e){form.querySelector('[role="alert"]').textContent=e.message;}finally{btn.disabled=false;}};
    };
    conteudo.querySelector('#comissao-exportar').onclick=async()=>{try{const r=escolhida();const out=await STORE.api({action:'performanceComissaoExportar',...periodo,id:r?.id});if(!out.ok)throw new Error(out.error);const url=URL.createObjectURL(new Blob([out.csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=out.arquivo;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);erro.textContent=out.aviso;}catch(e){erro.textContent=e.message;}};
  }catch(e){d.appendChild(Object.assign(document.createElement('p'),{textContent:e.message}));}
}
function comissaoEditar(fonte,ultima,periodo,pai,pessoas=[]) {
  const anterior=ultima?.entrada||{},config=anterior.config||{},rs=fonte.registros;
  const campo=(nome,rotulo,valor='',tipo='text')=>`<label>${rotulo}<input name="${nome}" type="${tipo}" ${tipo==='number'?'step="0.01" min="0" max="100"':''} value="${esc(valor??'')}"></label>`;
  const area=(nome,rotulo,valor='')=>`<label>${rotulo}<textarea name="${nome}" maxlength="2000">${esc(valor||'')}</textarea></label>`;
  const selecao=(nome,rotulo,valor,opcoes)=>`<label>${rotulo}<select name="${nome}">${opcoes.map(([v,t])=>`<option value="${v}" ${v===valor?'selected':''}>${t}</option>`).join('')}</select></label>`;
  const doc=(prefixo,d={})=>campo(prefixo+'origem','Origem (documento, foto, vistoria)',d.origem)+area(prefixo+'evidencia','Evidência (referência verificável)',d.evidencia)+area(prefixo+'justificativa','Decisão / justificativa',d.justificativa);
  const pessoa=(nome,rotulo,id='')=>`<label>${rotulo}<select name="${nome}"><option value="">Selecione a pessoa</option>${pessoas.map(p=>`<option value="${esc(p.id)}" ${p.id===id?'selected':''}>${esc(p.nome)} · cadastro ${esc(p.id)}</option>`).join('')}</select></label>`;
  const linhaRateio=(prefixo,p={})=>`<div data-rateio-linha>${pessoa(prefixo+'pessoa','Pessoa',p.pessoaId)}${campo(prefixo+'percentual','Participação (%)',p.cota==null?'':p.cota/100,'number')}<button type="button" class="btn-ghost" data-rateio-remover>Remover pessoa</button></div>`;
  const rateio=(prefixo,rotulo,ps=[])=>`<fieldset data-rateio="${prefixo}"><legend>${rotulo}</legend><div data-rateio-linhas>${ps.map(p=>linhaRateio(prefixo,p)).join('')}</div><button type="button" class="btn-ghost" data-rateio-adicionar="${prefixo}">Adicionar pessoa</button><p>As participações precisam somar 100%. A gestão confirma esta regra na aprovação.</p></fieldset>`;
  const gruposReconhecimento=COMISSAO.apurar(fonte,anterior).reconhecimento.equipes;
  const os=[...new Map(rs.map(r=>[r.osId||r.id,r])).values()];
  const d=perfDialog('Configurar apuração da comissão',`<form><p>Regra desta revisão: 1% do líquido entregue elegível; 20% internos quando elegíveis; restante da dupla 60% montador e 40% auxiliar. Valores da entrega já incluem descontos; não digite valores monetários aqui. Campos vazios geram pendência, sem aprovação automática.</p>
  ${selecao('modo','Situação do programa',config.modo||'teste',[['teste','Teste — sem pagamento'],['efetivo','Efetivo — exige decisão da gestão']])}${campo('inicio','Início efetivo autorizado',config.inicioEfetivo,'date')}${area('gestao','Decisão da gestão sobre início',config.decisaoGestao)}<label><input type="checkbox" name="extras" ${config.criteriosExtras==='somente_falha_comprovada'?'checked':''}> Validar atraso e retorno antecipado: nesta versão, somente falha comprovada da instalação zera pontos e comissão da O.S.</label>
  <details><summary>Configuração do reconhecimento (não escolhe campeão)</summary>${['elegibilidade','identidade','substituicoes','empates','premios','decisao'].map(k=>area('rec_'+k,{elegibilidade:'Equipes elegíveis, solo e composições avulsas',identidade:'Identidade da equipe durante o período',substituicoes:'Tratamento de substituições',empates:'Tratamento de empates',premios:'Prêmios autorizados e período aplicável',decisao:'Validação humana dos critérios'}[k],config.reconhecimento?.[k])).join('')}${gruposReconhecimento.map((g,i)=>`<fieldset><legend>${esc(g.nome)}${g.substituicao?' · substituição no período':''}${g.solo?' · solo':''}</legend><p>Composições preservadas: ${g.composicoes.map(ids=>ids.map(id=>esc(pessoas.find(p=>p.id===id)?.nome||id)).join(' + ')).join('; ')}</p>${selecao('req'+i,'Elegibilidade para reconhecimento',config.reconhecimento?.avaliacoes?.[g.chave]?.situacao,[['pendente','Pendente de decisão'],['elegivel','Elegível após revisão'],['inelegivel','Não elegível após revisão']])}${area('reqj'+i,'Justificativa',config.reconhecimento?.avaliacoes?.[g.chave]?.justificativa)}</fieldset>`).join('')}<p>Campeão e prêmio permanecem sujeitos a revisão específica. Nenhum vencedor anual é inferido deste período.</p></details>
  <label>Buscar O.S., cliente ou pessoa <input type="search" data-comissao-busca></label><p data-comissao-contagem></p><button type="button" class="btn-ghost" data-comissao-anterior>Anterior</button> <button type="button" class="btn-ghost" data-comissao-proxima>Próximas 10 conferências</button>
  ${os.map((r,i)=>{const x=anterior.decisoes?.[r.osId||r.id]||{};return `<details data-comissao-item data-busca="${esc(r.numero+' '+(r.cliente||''))}"><summary>Responsabilidade · O.S. ${esc(r.numero)} · ${esc(comissaoRotulo(x.decisao||'pendente'))}</summary><fieldset><legend>Decisão sobre responsabilidade</legend>${selecao('os'+i+'decisao','Decisão',x.decisao,[['pendente','Pendente'],['sem_falha','Sem falha comprovada após análise'],['falha_comprovada','Falha comprovada da instalação'],['abono','Abono justificado']])}${selecao('os'+i+'tipo','Tipo / origem da ocorrência',x.tipo,[['nenhuma','Nenhuma ocorrência após conferência'],['producao','Falha da produção'],['cliente','Mudança do cliente'],['incompleto','Serviço incompleto'],['ma_conducao','Má condução'],['atraso','Atraso'],['retorno_antecipado','Retorno antecipado'],['outra','Outra']])}${doc('os'+i,x)}</fieldset></details>`;}).join('')}
  ${rs.map((r,i)=>{const e=anterior.entregas?.[r.id]||{},interna=e.interna||{},gs=r.grupos?.length?r.grupos:[{membros:r.membros.map(m=>m.chave),cota:10000}];return `<details data-comissao-item data-busca="${esc(r.numero+' '+(r.cliente||'')+' '+r.membros.map(m=>m.nome).join(' '))}"><summary>Entrega · O.S. ${esc(r.numero)} · ${esc(comissaoData(r.dia))} · ${e.entregue?'conferência registrada':'pendente'}</summary><fieldset><legend>Entrega e participantes</legend><p>Base líquida preservada: ${comissaoDinheiro(Math.round(r.valor*100))}</p><label><input type="checkbox" name="e${i}entregue" ${e.entregue?'checked':''}> Entrega física comprovada</label>${doc('e'+i,e)}${r.membros.filter(m=>!/^\d{6}$/.test(m.chave)).map((m,j)=>pessoa('e'+i+'id'+j,`Resolver cadastro “${esc(m.nome)}”`,e.identidades?.[m.chave])).join('')}
  ${gs.map((g,j)=>{const x=e.grupos?.[j]||{};return `<h4>Equipe ${j+1} · ${g.cota/100}% da entrega</h4><p>${g.membros.map(ch=>{const p=r.membros.find(m=>String(m.chave)===String(ch));return esc(p?.nome||ch)+' · '+esc(ch);}).join(' / ')}</p>${g.membros.length===2?pessoa('e'+i+'g'+j+'montador','Montador (60%; auxiliar recebe 40%)',x.montadorId):rateio('e'+i+'g'+j+'partes','Participação de cada pessoa',x.partes)+area('e'+i+'g'+j+'justificativa','Justificativa do rateio solo, trio ou maior',x.justificativa)}`;}).join('')}
  ${selecao('e'+i+'interna','Montagem interna',interna.situacao,[['pendente','Pendente de análise'],['elegivel','Elegível — reservar 20%'],['impeditivo','Retrabalho impeditivo — parcela fica externa'],['nao_aplicavel','Não aplicável — parcela fica externa']])}${doc('e'+i+'int',interna)}${rateio('e'+i+'internas','Participação da montagem interna',interna.partes)}</fieldset></details>`;}).join('')}
  ${area('motivo','Motivo desta revisão')}<button class="btn-primary" type="submit">Salvar prévia calculada no servidor</button><p role="alert"></p></form>`);
  d.classList.add('comissao-dialog');
  d.querySelectorAll('[data-rateio-adicionar]').forEach(b=>b.onclick=()=>{const linhas=b.parentElement.querySelector('[data-rateio-linhas]');linhas.insertAdjacentHTML('beforeend',linhaRateio(b.dataset.rateioAdicionar));});
  d.onclick=ev=>{if(ev.target.matches('[data-rateio-remover]'))ev.target.closest('[data-rateio-linha]')?.remove();};
  let pagina=0;
  const filtrar=()=>{const busca=d.querySelector('[data-comissao-busca]').value.toLocaleLowerCase('pt-BR'),itens=[...d.querySelectorAll('[data-comissao-item]')],visiveis=itens.filter(e=>e.dataset.busca.toLocaleLowerCase('pt-BR').includes(busca));pagina=Math.min(pagina,Math.max(0,Math.ceil(visiveis.length/10)-1));itens.forEach(e=>e.hidden=true);visiveis.slice(pagina*10,pagina*10+10).forEach(e=>e.hidden=false);d.querySelector('[data-comissao-contagem]').textContent=`${visiveis.length} conferências · página ${pagina+1} de ${Math.max(1,Math.ceil(visiveis.length/10))}`;d.querySelector('[data-comissao-anterior]').disabled=pagina===0;d.querySelector('[data-comissao-proxima]').disabled=(pagina+1)*10>=visiveis.length;};
  d.querySelector('[data-comissao-busca]').oninput=()=>{pagina=0;filtrar();};d.querySelector('[data-comissao-anterior]').onclick=()=>{pagina--;filtrar();};d.querySelector('[data-comissao-proxima]').onclick=()=>{pagina++;filtrar();};filtrar();
  d.querySelector('form').onsubmit=async ev=>{
    ev.preventDefault();const form=ev.currentTarget,btn=form.querySelector('button[type="submit"]');btn.disabled=true;
    const v=n=>form.elements[n]?.value?.trim()||'',ck=n=>form.elements[n]?.checked===true;
    const documento=p=>({origem:v(p+'origem'),evidencia:v(p+'evidencia'),justificativa:v(p+'justificativa')});
    const partes=n=>[...form.querySelectorAll(`[data-rateio="${n}"] [data-rateio-linha]`)].map(l=>({pessoaId:l.querySelector('select').value,cota:Math.round(Number(l.querySelector('input').value)*100)}));
    const entrada={config:{modo:v('modo'),inicioEfetivo:v('inicio'),decisaoGestao:v('gestao'),criteriosExtras:ck('extras')?'somente_falha_comprovada':'pendente',reconhecimento:Object.fromEntries(['elegibilidade','identidade','substituicoes','empates','premios','decisao'].map(k=>[k,v('rec_'+k)]))},decisoes:{},entregas:{}};
    entrada.config.reconhecimento.avaliacoes=Object.fromEntries(gruposReconhecimento.map((g,i)=>[g.chave,{situacao:v('req'+i),justificativa:v('reqj'+i)}]));
    os.forEach((r,i)=>entrada.decisoes[r.osId||r.id]={...documento('os'+i),decisao:v('os'+i+'decisao'),tipo:v('os'+i+'tipo')});
    rs.forEach((r,i)=>{const gs=r.grupos?.length?r.grupos:[{membros:r.membros.map(m=>m.chave)}];entrada.entregas[r.id]={...documento('e'+i),entregue:ck('e'+i+'entregue'),identidades:Object.fromEntries(r.membros.filter(m=>!/^\d{6}$/.test(m.chave)).map((m,j)=>[m.chave,v('e'+i+'id'+j)])),grupos:gs.map((g,j)=>({montadorId:v('e'+i+'g'+j+'montador'),partes:partes('e'+i+'g'+j+'partes'),justificativa:v('e'+i+'g'+j+'justificativa')})),interna:{...documento('e'+i+'int'),situacao:v('e'+i+'interna'),partes:partes('e'+i+'internas')}};});
    try{const out=await STORE.api({action:'performanceComissaoNova',...periodo,fechamentoId:fonte.id,anterior:ultima?.id||'',entrada,motivo:v('motivo'),requestId:crypto.randomUUID()});if(!out.ok)throw new Error(out.error);d.close();await perfComissaoAbrir();}catch(e){form.querySelector('[role="alert"]').textContent=e.message;}finally{btn.disabled=false;}
  };
}
