/* Demandas da Agenda. Nenhuma chamada a saveOS/setCfg: vínculos são referências. */
'use strict';
const DEMANDAS=(()=>{
 const rotaInicial=new URLSearchParams(location.hash.slice(1));
 let dados=null,erro='',carregando=null,vista=rotaInicial.get('vista')==='demandas'?'demandas':'calendario',aberta=rotaInicial.get('demanda')||'',filtros={};
 const situacoes={aberta:'Aberta',em_andamento:'Em andamento',aguardando:'Aguardando providência',concluida:'Concluída',cancelada:'Cancelada'};
 const prioridades={baixa:'Baixa',normal:'Normal',alta:'Alta',urgente:'Urgente'};
 const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const uuid=()=>crypto.randomUUID(), hoje=()=>OPERACAO.dia(new Date()), fmt=d=>d?d.split('-').reverse().join('/'):'Sem prazo';
 const encerrada=d=>['concluida','cancelada'].includes(d.situacao);
 const pendentes=d=>d.acoes.filter(a=>!encerrada(a));
 const nome=id=>dados?.pessoas.find(p=>p.id===id)?.nome||id||'Não definido';
 const osNome=id=>{const o=dados?.ordens.find(o=>o.id===id);return o?`${o.numero||id} · ${o.cliente||''}`:`${id} · referência anterior`;};
 const dias=d=>d?Math.round((new Date(d+'T12:00:00')-new Date(hoje()+'T12:00:00'))/86400000):Infinity;
 const prazo=d=>encerrada(d)?situacoes[d.situacao]:dias(d.prazo)<0?'Atrasada':dias(d.prazo)<=3?'Prazo próximo':'Em aberto';
 async function api(operacao,args={}){const r=await STORE.api({action:'demandas',operacao,...args});if(!r?.ok)throw new Error(r?.error||'Não foi possível confirmar a operação.');return r;}
 async function carregar(forcar=false){if(carregando)return carregando;if(dados&&!forcar)return dados;carregando=api('listar').then(r=>{dados=r;erro='';return r;}).catch(x=>{erro=x.message;throw x;}).finally(()=>carregando=null);return carregando;}
 function rota(){const p=new URLSearchParams(location.hash.slice(1));p.set('aba','agenda');p.set('vista',vista);if(aberta)p.set('demanda',aberta);else p.delete('demanda');history.replaceState(null,'','#'+p);}
 function navegar(id=''){vista='demandas';aberta=id;rota();renderAgendaCasa();}
 function tabs(el){const nav=document.createElement('nav');nav.className='dm-tabs';nav.setAttribute('aria-label','Visões da Agenda');nav.innerHTML=`<button class="btn-ghost ${vista==='calendario'?'dm-selected':''}" data-dm-tab="calendario">Calendário</button><button class="btn-ghost ${vista==='demandas'?'dm-selected':''}" data-dm-tab="demandas">Demandas</button>`;el.prepend(nav);nav.onclick=ev=>{const b=ev.target.closest('[data-dm-tab]');if(b){vista=b.dataset.dmTab;aberta='';rota();renderAgendaCasa();}};}
 const btn=(label,attrs='')=>`<button type="button" class="btn-ghost btn-sm" ${attrs}>${label}</button>`;
 const options=(obj,valor)=>Object.entries(obj).map(([k,v])=>`<option value="${e(k)}" ${valor===k?'selected':''}>${e(v)}</option>`).join('');
 function badge(d){return `<span class="dm-badge dm-${d.situacao}">${e(situacoes[d.situacao]||d.situacao)}</span><span class="dm-badge dm-${d.prioridade}">${e(prioridades[d.prioridade])}</span>`;}
 function lista(){return dados.demandas.filter(d=>(!filtros.busca||(d.titulo+' '+d.descricao).toLowerCase().includes(filtros.busca.toLowerCase()))&&(!filtros.responsavel||d.responsavelId===filtros.responsavel)&&(!filtros.envolvido||d.envolvidos.includes(filtros.envolvido)||d.acoes.some(a=>a.responsavelId===filtros.envolvido))&&(!filtros.prioridade||d.prioridade===filtros.prioridade)&&(!filtros.situacao||d.situacao===filtros.situacao)&&(!filtros.os||d.osIds.includes(filtros.os))&&(!filtros.alerta||(filtros.alerta==='abertas'?!encerrada(d):filtros.alerta==='atrasadas'?!encerrada(d)&&(dias(d.prazo)<0||pendentes(d).some(a=>dias(a.prazo)<0)):filtros.alerta==='proximas'?!encerrada(d)&&(dias(d.prazo)>=0&&dias(d.prazo)<=3||pendentes(d).some(a=>dias(a.prazo)>=0&&dias(a.prazo)<=3)):d.situacao==='aguardando'||pendentes(d).some(a=>a.situacao==='aguardando')))).sort((a,b)=>Number(encerrada(a))-Number(encerrada(b))||(['urgente','alta','normal','baixa'].indexOf(a.prioridade)-['urgente','alta','normal','baixa'].indexOf(b.prioridade))||(a.prazo||'9999').localeCompare(b.prazo||'9999'));}
 async function render(el){
  el.innerHTML='<section class="dm-page"><p role="status">Carregando demandas…</p></section>';tabs(el);
  try{await carregar();}catch{el.querySelector('.dm-page').innerHTML=`<h2>Demandas</h2><p role="alert">${e(erro)}</p>${btn('Tentar novamente','data-retry')}`;el.querySelector('[data-retry]').onclick=()=>render(el);return;}
  if(!el.isConnected||vista!=='demandas')return;
  const box=el.querySelector('.dm-page');
  if(aberta){const d=dados.demandas.find(d=>d.id===aberta);if(d){detalhe(box,d);return;}aberta='';}
  const abertas=dados.demandas.filter(d=>!encerrada(d));
  box.innerHTML=`<header class="dm-head"><div><h2>Demandas</h2><p>Conecte pessoas e acompanhe a resolução de ponta a ponta.</p></div><div>${btn('Atualizar','data-refresh')} ${btn('+ Nova demanda','data-new')}</div></header>${erro?`<p role="alert">${e(erro)} · Exibindo a última consulta.</p>`:''}<div class="dm-summary"><button data-alerta="abertas"><b>${abertas.length}</b> Em aberto</button><button data-alerta="atrasadas"><b>${abertas.filter(d=>dias(d.prazo)<0||pendentes(d).some(a=>dias(a.prazo)<0)).length}</b> Atrasadas</button><button data-alerta="proximas"><b>${abertas.filter(d=>dias(d.prazo)>=0&&dias(d.prazo)<=3||pendentes(d).some(a=>dias(a.prazo)>=0&&dias(a.prazo)<=3)).length}</b> Próximos 3 dias</button><button data-alerta="aguardando"><b>${abertas.filter(d=>d.situacao==='aguardando'||pendentes(d).some(a=>a.situacao==='aguardando')).length}</b> Aguardando providência</button></div><div class="dm-filtros"><label>Pesquisar<input data-filter="busca" value="${e(filtros.busca)}" placeholder="Título ou descrição"></label>${[['responsavel','Responsável',Object.fromEntries(dados.pessoas.map(p=>[p.id,p.nome]))],['envolvido','Pessoa envolvida',Object.fromEntries(dados.pessoas.map(p=>[p.id,p.nome]))],['prioridade','Prioridade',prioridades],['situacao','Situação',situacoes],['os','O.S. relacionada',Object.fromEntries(dados.ordens.map(o=>[o.id,osNome(o.id)]))]].map(([k,n,op])=>`<label>${n}<select data-filter="${k}"><option value="">Todos</option>${options(op,filtros[k])}</select></label>`).join('')}${btn('Limpar filtros','data-clear')}</div><p class="dm-muted">Atualizado em ${e(new Date(dados.atualizadoEm).toLocaleString('pt-BR'))}. ${filtros.alerta?'Filtro de atenção ativo.':''}</p><div class="dm-grid">${lista().map(d=>{const feitas=d.acoes.filter(a=>a.situacao==='concluida').length;return `<article class="dm-card">${badge(d)}<h3>${e(d.titulo)}</h3><p>${e(d.resultadoEsperado)}</p><p><b>${e(nome(d.responsavelId))}</b> · ${e(fmt(d.prazo))}</p><p class="${prazo(d)==='Atrasada'?'dm-atraso':''}">${e(prazo(d))} · ${feitas}/${d.acoes.length} ações concluídas</p><progress value="${feitas}" max="${d.acoes.length||1}" aria-label="Ações concluídas"></progress><p class="dm-muted">${d.envolvidos.length} pessoa(s) · ${d.osIds.length} O.S. de referência</p>${btn('Acompanhar demanda',`data-open="${e(d.id)}"`)}</article>`;}).join('')||'<div class="dm-card"><h3>Nenhuma demanda neste recorte</h3><p>Crie uma demanda para coordenar uma situação que precisa de várias providências.</p></div>'}</div>`;
  box.querySelector('[data-new]').onclick=()=>editar();box.querySelector('[data-refresh]').onclick=async()=>{try{await carregar(true);}catch{}render(el);};box.querySelector('[data-clear]').onclick=()=>{filtros={};render(el);};
  box.querySelectorAll('[data-filter]').forEach(n=>n.onchange=()=>{filtros[n.dataset.filter]=n.value;render(el);});box.querySelectorAll('[data-alerta]').forEach(n=>n.onclick=()=>{filtros.alerta=n.dataset.alerta;render(el);});box.querySelectorAll('[data-open]').forEach(n=>n.onclick=()=>navegar(n.dataset.open));
 }
 function detalhe(box,d){const prox=pendentes(d).sort((a,b)=>(a.prazo||'9999').localeCompare(b.prazo||'9999'))[0];box.innerHTML=`<header class="dm-head"><div>${btn('← Todas as demandas','data-back')}<h2>${e(d.titulo)}</h2>${badge(d)}</div>${btn('Editar e registrar atualização','data-edit')}</header><div class="dm-next"><b>Próximo passo</b><p>${encerrada(d)?'Demanda encerrada.':prox?`${e(prox.titulo)} · ${e(nome(prox.responsavelId))} · ${e(fmt(prox.prazo))}`:'Definir a próxima ação com o responsável.'}</p></div><div class="dm-grid"><section class="dm-card"><h3>O que está acontecendo</h3><p class="dm-text">${e(d.descricao)}</p><h3>Resultado esperado</h3><p class="dm-text">${e(d.resultadoEsperado)}</p><p>Coordenação: <b>${e(nome(d.responsavelId))}</b></p><p>Prazo: ${e(fmt(d.prazo))} · ${e(prazo(d))}</p><h3>Pessoas envolvidas</h3><p>${d.envolvidos.map(p=>e(nome(p))).join(' · ')||'Nenhuma pessoa adicional'}</p><h3>O.S. relacionadas</h3><p>${d.osIds.map(id=>e(osNome(id))).join('<br>')||'Sem O.S. vinculada'}</p><small>Referências de contexto. Nenhuma ação desta demanda altera a O.S.</small></section><section class="dm-card"><h3>Providências · ${d.acoes.filter(a=>a.situacao==='concluida').length}/${d.acoes.length} concluídas</h3>${d.acoes.map(a=>`<article class="dm-action"><b>${e(a.titulo)}</b><p>${e(nome(a.responsavelId))} · ${e(fmt(a.prazo))}</p><span class="dm-badge">${e(a.situacao==='pendente'?'Pendente':situacoes[a.situacao])}</span>${!encerrada(a)&&dias(a.prazo)<0?'<strong class="dm-atraso"> Ação atrasada</strong>':''}</article>`).join('')||'<p>Nenhuma ação cadastrada.</p>'}</section></div><section class="dm-card"><h3>Atualizações e decisões</h3>${(d.atualizacoes||[]).map(a=>`<article class="dm-action"><p class="dm-text">${e(a.texto)}</p><small>${e(a.por)} · ${e(new Date(a.em).toLocaleString('pt-BR'))}</small></article>`).join('')||'<p>Ainda sem atualizações.</p>'}</section><section class="dm-card"><h3>Arquivos e referências</h3><p>PDF, PNG ou JPEG até 10 MB. Para outros formatos, registre um link na edição.</p>${(d.anexos||[]).map(a=>a.url?`<p><a href="${e(a.url)}" target="_blank" rel="noopener noreferrer">${e(a.nome)} ↗</a></p>`:`<p>${btn(e(a.nome),`data-file="${e(a.id)}"`)}</p>`).join('')}<label>Adicionar arquivo<input type="file" data-upload accept="application/pdf,image/png,image/jpeg"></label><p data-msg role="status"></p></section><details class="dm-card"><summary>Histórico de alterações · ${(d.historico||[]).length}</summary>${(d.historico||[]).slice().reverse().map(h=>`<p>${e(h.evento)} · ${e(h.por)} · ${e(new Date(h.em).toLocaleString('pt-BR'))}${h.antes?`<small> · Antes: ${e(situacoes[h.antes.situacao])}, prazo ${e(fmt(h.antes.prazo))}</small>`:''}</p>`).join('')}</details><p class="dm-muted">Criada por ${e(d.criadoPor)} · Atualizada por ${e(d.atualizadoPor)} em ${e(new Date(d.atualizadoEm).toLocaleString('pt-BR'))}</p>`;
  box.querySelector('[data-back]').onclick=()=>navegar();box.querySelector('[data-edit]').onclick=()=>editar(d);
  box.querySelectorAll('[data-file]').forEach(b=>b.onclick=async()=>{try{const r=await api('arquivo',{id:d.id,arquivoId:b.dataset.file});const a=document.createElement('a');a.href=r.url;a.target='_blank';a.rel='noopener noreferrer';a.click();}catch(x){box.querySelector('[data-msg]').textContent=x.message;}});
  box.querySelector('[data-upload]').onchange=async ev=>{const input=ev.target,f=input.files[0],msg=box.querySelector('[data-msg]');if(!f)return;if(f.size>10000000){msg.textContent='Limite de 10 MB.';return;}input.disabled=true;msg.textContent='Enviando arquivo…';try{const base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(f);});await api('anexar',{id:d.id,nome:f.name,base64,expectedRevision:d.revision,mutationId:uuid()});await carregar(true);navegar(d.id);}catch(x){msg.textContent=x.message+' · Se a resposta se perdeu, atualize a demanda antes de tentar de novo.';input.disabled=false;}};
 }
 function editar(original){
 const d=original?structuredClone(original):{id:uuid(),titulo:'',descricao:'',resultadoEsperado:'',responsavelId:'',envolvidos:[],osIds:[],prioridade:'normal',situacao:'aberta',prazo:'',acoes:[],revision:0};
 const dlg=document.createElement('dialog');dlg.className='dm-dialog';dlg.setAttribute('aria-label',original?'Editar demanda':'Nova demanda');
 const input=(n,label,type='text',required=false)=>`<label>${label}<input name="${n}" type="${type}" value="${e(d[n])}" ${required?'required':''} maxlength="200"></label>`;
 const ps=Object.fromEntries(dados.pessoas.map(p=>[p.id,p.nome+(p.setor?' · '+p.setor:'')+(p.inativo?' · vínculo anterior':'')]));
 dlg.innerHTML=`<form><header class="dm-head"><h2>${original?'Editar demanda':'Nova demanda'}</h2>${btn('Fechar','data-close')}</header><p class="dm-muted">As O.S. são apenas referências. A demanda tem ações e prazos próprios.</p><div class="dm-form">${input('titulo','Título','text',true)}<label>Responsável principal<select name="responsavelId" required><option value="">Selecione no RH</option>${options(ps,d.responsavelId)}</select></label><label class="dm-wide">Situação / necessidade<textarea name="descricao" required maxlength="12000">${e(d.descricao)}</textarea></label><label class="dm-wide">Resultado esperado<textarea name="resultadoEsperado" required maxlength="4000">${e(d.resultadoEsperado)}</textarea></label><label>Prioridade<select name="prioridade">${options(prioridades,d.prioridade)}</select></label><label>Andamento<select name="situacao">${options(situacoes,d.situacao)}</select></label>${input('prazo','Prazo da demanda','date')}<label>Pesquisar pessoas<input data-people-search placeholder="Nome ou setor"></label><fieldset class="dm-wide"><legend>Pessoas envolvidas · RH</legend><div class="dm-picker">${dados.pessoas.map(p=>`<label data-person-text="${e((p.nome+' '+(p.setor||'')).toLowerCase())}"><input type="checkbox" name="envolvidos" value="${e(p.id)}" ${d.envolvidos.includes(p.id)?'checked':''}> ${e(ps[p.id])}</label>`).join('')}</div></fieldset><fieldset class="dm-wide"><legend>O.S. relacionadas (opcional)</legend><input data-os-search placeholder="Buscar número ou cliente" aria-label="Buscar O.S."><div class="dm-picker" data-os-picker></div></fieldset><section class="dm-wide"><h3>Ações necessárias</h3><div data-actions></div>${btn('+ Adicionar ação','data-add-action')}</section><label class="dm-wide">Registrar atualização ou decisão<textarea name="nota" maxlength="8000" placeholder="O que aconteceu? O que foi decidido?"></textarea></label><label>Nome da referência<input name="linkNome" maxlength="200"></label><label>Link de apoio (opcional)<input name="linkUrl" type="url" placeholder="https://"></label></div><p role="alert" data-error></p><footer>${btn('Cancelar','data-close')}<button type="submit" class="btn-primary">Salvar demanda</button></footer></form>`;
 document.body.append(dlg);dlg.showModal();dlg.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dlg.close());dlg.onclose=()=>dlg.remove();
 dlg.querySelector('[data-people-search]').oninput=ev=>dlg.querySelectorAll('[data-person-text]').forEach(l=>l.hidden=!l.dataset.personText.includes(ev.target.value.toLowerCase())&&!l.querySelector('input').checked);
 const osSet=new Set(d.osIds);function mostrarOS(){const termo=dlg.querySelector('[data-os-search]').value.toLowerCase();const all=[...dados.ordens,...d.osIds.filter(id=>!dados.ordens.some(o=>o.id===id)).map(id=>({id}))];const res=all.filter(o=>osSet.has(o.id)||osNome(o.id).toLowerCase().includes(termo)).sort((a,b)=>Number(osSet.has(b.id))-Number(osSet.has(a.id)));dlg.querySelector('[data-os-picker]').innerHTML=res.slice(0,80).map(o=>`<label><input type="checkbox" value="${e(o.id)}" ${osSet.has(o.id)?'checked':''}> ${e(osNome(o.id))}</label>`).join('')+(res.length>80?'<p>Refine a busca para localizar outras O.S.</p>':'');dlg.querySelectorAll('[data-os-picker] input').forEach(n=>n.onchange=()=>n.checked?osSet.add(n.value):osSet.delete(n.value));}mostrarOS();dlg.querySelector('[data-os-search]').oninput=mostrarOS;
 const aBox=dlg.querySelector('[data-actions]');function addAcao(a){const row=document.createElement('div');row.className='dm-action dm-form';row.dataset.id=a.id;row.innerHTML=`<label>Ação<input data-a="titulo" required maxlength="400" value="${e(a.titulo)}"></label><label>Responsável<select data-a="responsavelId" required><option value="">Selecione</option>${options(ps,a.responsavelId)}</select></label><label>Prazo<input type="date" data-a="prazo" value="${e(a.prazo)}"></label><label>Situação<select data-a="situacao">${options({pendente:'Pendente',em_andamento:'Em andamento',aguardando:'Aguardando providência',concluida:'Concluída',cancelada:'Cancelada'},a.situacao)}</select></label>`;aBox.append(row);}d.acoes.forEach(addAcao);dlg.querySelector('[data-add-action]').onclick=()=>addAcao({id:uuid(),situacao:'pendente'});
 let tentativa='',mutationId='';dlg.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const f=new FormData(ev.target),n={...d};['titulo','descricao','resultadoEsperado','responsavelId','prazo','situacao','prioridade'].forEach(k=>n[k]=f.get(k));n.envolvidos=f.getAll('envolvidos');n.osIds=[...osSet];n.acoes=[...aBox.children].map(r=>{const a={id:r.dataset.id};r.querySelectorAll('[data-a]').forEach(el=>a[el.dataset.a]=el.value);return a;});const payload={demanda:n,expectedRevision:d.revision,nota:f.get('nota'),...(f.get('linkUrl')?{link:{nome:f.get('linkNome'),url:f.get('linkUrl')}}:{})};const serial=JSON.stringify(payload);if(serial!==tentativa){mutationId=uuid();tentativa=serial;}const b=ev.target.querySelector('[type=submit]');b.disabled=true;dlg.querySelector('[data-error]').textContent='Salvando…';try{await api('salvar',{...payload,mutationId});dlg.close();try{await carregar(true);}catch{dados=null;}navegar(d.id);}catch(x){dlg.querySelector('[data-error]').textContent=x.message;b.disabled=false;}};
 }
 async function integrar(el,mes,dia){tabs(el);const ref=document.createElement('section');ref.className='dm-calendar';ref.innerHTML='<p class="dm-muted">Consultando prazos das demandas…</p>';el.querySelector('.casa-dia-painel')?.append(ref);try{await carregar(true);if(!ref.isConnected)return;const prazos=dados.demandas.filter(d=>!encerrada(d)).flatMap(d=>[...(d.prazo?[{id:d.id,data:d.prazo,titulo:d.titulo,tipo:'Demanda'}]:[]),...pendentes(d).filter(a=>a.prazo).map(a=>({id:d.id,data:a.prazo,titulo:a.titulo,tipo:'Ação · '+d.titulo}))]);el.querySelectorAll('[data-dia]').forEach(b=>{const n=prazos.filter(p=>p.data===b.dataset.dia).length;if(n){const s=document.createElement('span');s.className='casa-pill dm-pill';s.textContent=n+' prazo(s)';b.append(s);b.setAttribute('aria-label',b.getAttribute('aria-label')+', '+n+' prazos de demandas');}});ref.innerHTML=`<h3>Demandas neste dia</h3>${prazos.filter(p=>p.data===dia).map(p=>`<p>${btn(e(p.titulo),`data-open="${e(p.id)}"`)}<small>${e(p.tipo)}</small></p>`).join('')||'<p class="dm-muted">Nenhum prazo de demanda ou ação neste dia.</p>'}${btn('Ver todas as demandas','data-all')}`;ref.querySelector('[data-all]').onclick=()=>navegar();ref.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>navegar(b.dataset.open));}catch(x){if(ref.isConnected)ref.innerHTML=`<p class="dm-muted">Demandas: ${e(x.message)}</p>`;}}
 return {ativa:()=>vista==='demandas',render,integrar};
})();
