// frases.js — Frases motivacionais curtas (barra superior e comemorações).
// Cada item: { t: texto, a: autor }. ~500 frases.
'use strict';

const FRASES = [
  {t:"Acredite que você pode e já estará no meio do caminho.", a:"Theodore Roosevelt"},
  {t:"O sucesso é a soma de pequenos esforços repetidos dia após dia.", a:"Robert Collier"},
  {t:"A persistência é o caminho do êxito.", a:"Charles Chaplin"},
  {t:"Não espere por uma oportunidade. Crie-a.", a:"George Bernard Shaw"},
  {t:"Faça o que você ama e nunca trabalhará um dia na vida.", a:"Confúcio"},
  {t:"Grandes coisas nunca vêm de zonas de conforto.", a:"Anônimo"},
  {t:"O futuro pertence a quem acredita na beleza dos seus sonhos.", a:"Eleanor Roosevelt"},
  {t:"Você perde 100% das chances que não arrisca.", a:"Wayne Gretzky"},
  {t:"A jornada de mil milhas começa com um passo.", a:"Lao-Tsé"},
  {t:"Tudo parece impossível até que seja feito.", a:"Nelson Mandela"},
  {t:"A disciplina é a ponte entre metas e realizações.", a:"Jim Rohn"},
  {t:"Sonhe grande e ouse falhar.", a:"Norman Vaughan"},
  {t:"Não conte os dias, faça os dias contarem.", a:"Muhammad Ali"},
  {t:"Caia sete vezes, levante oito.", a:"Provérbio japonês"},
  {t:"A melhor maneira de prever o futuro é criá-lo.", a:"Peter Drucker"},
  {t:"Comece onde você está. Use o que você tem. Faça o que você pode.", a:"Arthur Ashe"},
  {t:"O segredo de ir em frente é começar.", a:"Mark Twain"},
  {t:"Energia e persistência conquistam todas as coisas.", a:"Benjamin Franklin"},
  {t:"Quem tem um porquê enfrenta qualquer como.", a:"Friedrich Nietzsche"},
  {t:"A qualidade nunca é um acidente; é sempre resultado de esforço inteligente.", a:"John Ruskin"},
  {t:"Trabalhe duro em silêncio e deixe o sucesso fazer o barulho.", a:"Frank Ocean"},
  {t:"A motivação te faz começar; o hábito te mantém indo.", a:"Jim Ryun"},
  {t:"Excelência não é um ato, mas um hábito.", a:"Aristóteles"},
  {t:"O único lugar onde o sucesso vem antes do trabalho é no dicionário.", a:"Vidal Sassoon"},
  {t:"Não tenha medo de desistir do bom para perseguir o ótimo.", a:"John D. Rockefeller"},
  {t:"Pequenos progressos ainda são progressos.", a:"Anônimo"},
  {t:"Sua atitude, não sua aptidão, determina sua altitude.", a:"Zig Ziglar"},
  {t:"O que você faz hoje pode melhorar todos os seus amanhãs.", a:"Ralph Marston"},
  {t:"Coragem não é a ausência de medo, mas o triunfo sobre ele.", a:"Nelson Mandela"},
  {t:"Faça hoje o que os outros não fazem para ter amanhã o que os outros não têm.", a:"Jerry Rice"},
  {t:"A diferença entre o impossível e o possível está na determinação.", a:"Tommy Lasorda"},
  {t:"Não diminua seu sonho para caber na realidade; aumente sua fé.", a:"Anônimo"},
  {t:"O esforço de hoje é o resultado de amanhã.", a:"Anônimo"},
  {t:"Vencer é uma questão de querer.", a:"Ayrton Senna"},
  {t:"No que diz respeito ao desempenho, ao compromisso, ao esforço, à dedicação, não existe meio termo.", a:"Ayrton Senna"},
  {t:"Sou capaz de superar meus limites quando a vontade é maior que o medo.", a:"Ayrton Senna"},
  {t:"Se você quer ser bem-sucedido, precisa de dedicação total.", a:"Ayrton Senna"},
  {t:"O talento vence jogos, mas o trabalho em equipe vence campeonatos.", a:"Michael Jordan"},
  {t:"Eu falhei várias vezes, e é por isso que tenho sucesso.", a:"Michael Jordan"},
  {t:"Limites, como medos, muitas vezes são apenas ilusões.", a:"Michael Jordan"},
  {t:"Alguns querem que aconteça, outros desejam que aconteça, e outros fazem acontecer.", a:"Michael Jordan"},
  {t:"O importante não é vencer todos os dias, mas lutar sempre.", a:"Waldemar Valle Martins"},
  {t:"A persistência realiza o impossível.", a:"Provérbio chinês"},
  {t:"O fracasso é a oportunidade de começar de novo, com mais inteligência.", a:"Henry Ford"},
  {t:"Se você pensa que pode ou que não pode, de qualquer forma você está certo.", a:"Henry Ford"},
  {t:"Juntar-se é um começo, manter-se juntos é um progresso, trabalhar juntos é sucesso.", a:"Henry Ford"},
  {t:"Obstáculos são aquelas coisas assustadoras que você vê quando tira os olhos do seu objetivo.", a:"Henry Ford"},
  {t:"Quer você pense que consegue ou não, você tem razão.", a:"Henry Ford"},
  {t:"A imaginação é mais importante que o conhecimento.", a:"Albert Einstein"},
  {t:"No meio da dificuldade encontra-se a oportunidade.", a:"Albert Einstein"},
  {t:"A vida é como andar de bicicleta: para manter o equilíbrio, é preciso se manter em movimento.", a:"Albert Einstein"},
  {t:"Tente não se tornar um homem de sucesso, mas sim um homem de valor.", a:"Albert Einstein"},
  {t:"Loucura é fazer a mesma coisa repetidamente e esperar resultados diferentes.", a:"Albert Einstein"},
  {t:"A mente que se abre a uma nova ideia jamais volta ao seu tamanho original.", a:"Albert Einstein"},
  {t:"Não é que eu seja tão inteligente, é que eu fico mais tempo com os problemas.", a:"Albert Einstein"},
  {t:"Inovação distingue um líder de um seguidor.", a:"Steve Jobs"},
  {t:"Seu tempo é limitado, não o desperdice vivendo a vida de outra pessoa.", a:"Steve Jobs"},
  {t:"A única maneira de fazer um excelente trabalho é amar o que você faz.", a:"Steve Jobs"},
  {t:"Continue faminto, continue tolo.", a:"Steve Jobs"},
  {t:"Detalhes fazem a perfeição, e a perfeição não é um detalhe.", a:"Leonardo da Vinci"},
  {t:"Simplicidade é o último grau de sofisticação.", a:"Leonardo da Vinci"},
  {t:"Quem não valoriza a vida, não a merece.", a:"Leonardo da Vinci"},
  {t:"A felicidade não é algo pronto. Ela vem de suas próprias ações.", a:"Dalai Lama"},
  {t:"Compartilhe seu conhecimento. É uma forma de alcançar a imortalidade.", a:"Dalai Lama"},
  {t:"Lembre-se de que nem sempre conseguir o que quer é um golpe de sorte.", a:"Dalai Lama"},
  {t:"Educação é a arma mais poderosa que você pode usar para mudar o mundo.", a:"Nelson Mandela"},
  {t:"Eu nunca perco. Ou eu ganho, ou eu aprendo.", a:"Nelson Mandela"},
  {t:"Que seus esforços desafiem as impossibilidades.", a:"Jamie Paolinetti"},
  {t:"A mente é tudo. O que você pensa, você se torna.", a:"Buda"},
  {t:"Não há caminho para a felicidade; a felicidade é o caminho.", a:"Buda"},
  {t:"Cada manhã nascemos de novo. O que fazemos hoje é o que mais importa.", a:"Buda"},
  {t:"Três coisas não podem ser escondidas: o sol, a lua e a verdade.", a:"Buda"},
  {t:"Você é o que você faz repetidamente.", a:"Aristóteles"},
  {t:"Conhecer a si mesmo é o começo de toda sabedoria.", a:"Aristóteles"},
  {t:"A esperança é o sonho do homem acordado.", a:"Aristóteles"},
  {t:"O todo é maior que a soma das partes.", a:"Aristóteles"},
  {t:"Conheça-te a ti mesmo.", a:"Sócrates"},
  {t:"Só sei que nada sei.", a:"Sócrates"},
  {t:"A vida não examinada não vale a pena ser vivida.", a:"Sócrates"},
  {t:"Penso, logo existo.", a:"René Descartes"},
  {t:"Não é o mais forte que sobrevive, mas o que melhor se adapta.", a:"Charles Darwin"},
  {t:"Se cheguei até aqui foi porque me apoiei no ombro de gigantes.", a:"Isaac Newton"},
  {t:"O que sabemos é uma gota; o que ignoramos é um oceano.", a:"Isaac Newton"},
  {t:"A ciência é o conhecimento organizado. A sabedoria é a vida organizada.", a:"Immanuel Kant"},
  {t:"Atreve-te a saber.", a:"Immanuel Kant"},
  {t:"Aquilo que não me mata me fortalece.", a:"Friedrich Nietzsche"},
  {t:"Sem música, a vida seria um erro.", a:"Friedrich Nietzsche"},
  {t:"Torne-te quem você é.", a:"Friedrich Nietzsche"},
  {t:"O homem é a medida de todas as coisas.", a:"Protágoras"},
  {t:"Conta-me e eu esqueço. Ensina-me e eu lembro. Envolve-me e eu aprendo.", a:"Benjamin Franklin"},
  {t:"Um investimento em conhecimento paga sempre os melhores juros.", a:"Benjamin Franklin"},
  {t:"Por falta de um prego, perdeu-se a ferradura.", a:"Benjamin Franklin"},
  {t:"Bem feito é melhor que bem dito.", a:"Benjamin Franklin"},
  {t:"Cuide dos pequenos gastos; um pequeno furo afunda um navio.", a:"Benjamin Franklin"},
  {t:"Não deixe para amanhã o que você pode fazer hoje.", a:"Benjamin Franklin"},
  {t:"A felicidade humana geralmente não é alcançada por grandes golpes de sorte, mas por pequenas vantagens diárias.", a:"Benjamin Franklin"},
  {t:"O homem que move montanhas começa carregando pequenas pedras.", a:"Confúcio"},
  {t:"Não importa o quão devagar você vá, desde que não pare.", a:"Confúcio"},
  {t:"Quando é óbvio que as metas não podem ser atingidas, ajuste as ações.", a:"Confúcio"},
  {t:"Aprender sem pensar é tempo perdido.", a:"Confúcio"},
  {t:"Exija muito de si mesmo e espere pouco dos outros.", a:"Confúcio"},
  {t:"Onde quer que você vá, vá com todo o seu coração.", a:"Confúcio"},
  {t:"A vida é simples, mas insistimos em complicá-la.", a:"Confúcio"},
  {t:"Escolha um trabalho que ame e não terás de trabalhar nem um dia.", a:"Confúcio"},
  {t:"O homem superior é modesto no falar, mas excede no agir.", a:"Confúcio"},
  {t:"Estuda o passado se queres prever o futuro.", a:"Confúcio"},
  {t:"A coisa mais difícil é a decisão de agir; o resto é mera tenacidade.", a:"Amelia Earhart"},
  {t:"O melhor caminho para começar é parar de falar e começar a fazer.", a:"Walt Disney"},
  {t:"Se você pode sonhar, você pode fazer.", a:"Walt Disney"},
  {t:"Todos os nossos sonhos podem se tornar realidade se tivermos coragem de persegui-los.", a:"Walt Disney"},
  {t:"A maneira de começar é parar de falar e começar a agir.", a:"Walt Disney"},
  {t:"É divertido fazer o impossível.", a:"Walt Disney"},
  {t:"Tudo o que você pode imaginar é real.", a:"Pablo Picasso"},
  {t:"A inspiração existe, mas tem que te encontrar trabalhando.", a:"Pablo Picasso"},
  {t:"Ação é a chave fundamental para todo sucesso.", a:"Pablo Picasso"},
  {t:"Aprenda as regras como um profissional para quebrá-las como um artista.", a:"Pablo Picasso"},
  {t:"A criatividade exige coragem.", a:"Henri Matisse"},
  {t:"A arte lava da alma a poeira do dia a dia.", a:"Pablo Picasso"},
  {t:"Onde há vontade, há um caminho.", a:"Provérbio"},
  {t:"Cada dia é uma nova chance de mudar sua vida.", a:"Anônimo"},
  {t:"Não desperdice tempo explicando; as pessoas só ouvem o que querem.", a:"Paulo Coelho"},
  {t:"Quando você quer alguma coisa, todo o universo conspira para que você realize.", a:"Paulo Coelho"},
  {t:"O mundo está nas mãos daqueles que têm coragem de sonhar e de correr o risco.", a:"Paulo Coelho"},
  {t:"Um dia ou dia um. Você decide.", a:"Paulo Coelho"},
  {t:"A possibilidade de realizarmos um sonho é o que torna a vida interessante.", a:"Paulo Coelho"},
  {t:"Talvez a viagem não te traga riqueza, mas te trará sabedoria.", a:"Paulo Coelho"},
  {t:"As pessoas nunca desistem dos seus sonhos por serem impossíveis, mas por falta de coragem.", a:"Paulo Coelho"},
  {t:"O segredo da vida é cair sete vezes e levantar oito.", a:"Paulo Coelho"},
  {t:"Conhecimento não é aquilo que você sabe, mas o que você faz com aquilo que sabe.", a:"Aldous Huxley"},
  {t:"Vai valer a pena, eu prometo.", a:"Anônimo"},
  {t:"Transforme suas feridas em sabedoria.", a:"Oprah Winfrey"},
  {t:"A maior aventura é o que está por vir.", a:"Anônimo"},
  {t:"Faça de cada dia sua obra-prima.", a:"John Wooden"},
  {t:"As coisas funcionam melhor para quem aproveita ao máximo como as coisas funcionam.", a:"John Wooden"},
  {t:"Não deixe que o que você não pode fazer interfira no que você pode fazer.", a:"John Wooden"},
  {t:"O sucesso normalmente vem para quem está ocupado demais para procurá-lo.", a:"Henry David Thoreau"},
  {t:"Vá com confiança na direção dos seus sonhos. Viva a vida que você imaginou.", a:"Henry David Thoreau"},
  {t:"Não é suficiente estar ocupado; a questão é: com o quê?", a:"Henry David Thoreau"},
  {t:"O que está atrás de nós e o que está à nossa frente são pequenos comparados ao que está dentro de nós.", a:"Ralph Waldo Emerson"},
  {t:"Faça o que você teme e a morte do medo é certa.", a:"Ralph Waldo Emerson"},
  {t:"O único limite para o nosso amanhã são as dúvidas de hoje.", a:"Franklin D. Roosevelt"},
  {t:"Quando você chegar ao fim da corda, dê um nó e segure firme.", a:"Franklin D. Roosevelt"},
  {t:"Coragem é resistência ao medo, domínio do medo, não ausência de medo.", a:"Mark Twain"},
  {t:"Daqui a vinte anos você estará mais decepcionado pelas coisas que não fez.", a:"Mark Twain"},
  {t:"O bom humor é uma das melhores peças de roupa que se pode usar em sociedade.", a:"William Thackeray"},
  {t:"Os dois dias mais importantes da sua vida: o dia em que você nasceu e o dia em que descobre por quê.", a:"Mark Twain"},
  {t:"Bondade é a linguagem que o surdo pode ouvir e o cego pode ver.", a:"Mark Twain"},
  {t:"Continue caminhando e não olhe para trás.", a:"Anônimo"},
  {t:"O otimista vê oportunidade em cada dificuldade.", a:"Winston Churchill"},
  {t:"O sucesso é ir de fracasso em fracasso sem perder o entusiasmo.", a:"Winston Churchill"},
  {t:"Nunca, nunca, nunca desista.", a:"Winston Churchill"},
  {t:"Se você está atravessando o inferno, continue andando.", a:"Winston Churchill"},
  {t:"A coragem é o que é preciso para levantar e falar; também é o que é preciso para sentar e ouvir.", a:"Winston Churchill"},
  {t:"Atitude é uma pequena coisa que faz uma grande diferença.", a:"Winston Churchill"},
  {t:"Não basta ter conhecimento, é preciso aplicá-lo.", a:"Johann Goethe"},
  {t:"Quem não sabe para onde vai, qualquer caminho serve.", a:"Lewis Carroll"},
  {t:"Conhecimento fala, mas sabedoria escuta.", a:"Jimi Hendrix"},
  {t:"Não tenha medo da perfeição: você nunca a alcançará.", a:"Salvador Dalí"},
  {t:"A persistência é o menor caminho do êxito.", a:"Charles Chaplin"},
  {t:"A vida é uma peça de teatro que não permite ensaios.", a:"Charles Chaplin"},
  {t:"Um dia sem sorrir é um dia desperdiçado.", a:"Charles Chaplin"},
  {t:"Para crescer, é preciso sonhar grande.", a:"Anônimo"},
  {t:"A persistência é o caminho do êxito.", a:"Charles Chaplin"},
  {t:"O importante não é o que fizeram de você, mas o que você faz com o que fizeram de você.", a:"Jean-Paul Sartre"},
  {t:"Somos nossas escolhas.", a:"Jean-Paul Sartre"},
  {t:"O homem está condenado a ser livre.", a:"Jean-Paul Sartre"},
  {t:"Tudo posso naquele que me fortalece.", a:"São Paulo"},
  {t:"A fé é a certeza daquilo que esperamos.", a:"Bíblia"},
  {t:"Tudo tem o seu tempo determinado.", a:"Eclesiastes"},
  {t:"O conhecimento é a única coisa que ninguém pode tirar de você.", a:"B. B. King"},
  {t:"O preço da grandeza é a responsabilidade.", a:"Winston Churchill"},
  {t:"Faça o melhor que puder até saber fazer melhor. Então, faça melhor.", a:"Maya Angelou"},
  {t:"As pessoas vão esquecer o que você disse, mas nunca como você as fez sentir.", a:"Maya Angelou"},
  {t:"Não fui derrotada por nada. Tenho dentro de mim a força de um leão.", a:"Maya Angelou"},
  {t:"Você pode encontrar muitas derrotas, mas não deve ser derrotado.", a:"Maya Angelou"},
  {t:"Nada vai funcionar a menos que você funcione.", a:"Maya Angelou"},
  {t:"A vida ama ser levada às últimas consequências.", a:"Clarice Lispector"},
  {t:"Liberdade é pouco. O que eu desejo ainda não tem nome.", a:"Clarice Lispector"},
  {t:"Que ninguém se engane: só se consegue a simplicidade através de muito trabalho.", a:"Clarice Lispector"},
  {t:"Eu sou aquela mulher a quem o tempo muito ensinou.", a:"Cora Coralina"},
  {t:"Feliz aquele que transfere o que sabe e aprende o que ensina.", a:"Cora Coralina"},
  {t:"O saber a gente aprende com os mestres e os livros; a sabedoria, com a vida.", a:"Cora Coralina"},
  {t:"Mesmo quando tudo parece desabar, cabe a mim decidir entre rir ou chorar.", a:"Cora Coralina"},
  {t:"Que nada nos defina, que nada nos sujeite. Que a liberdade seja a nossa própria substância.", a:"Simone de Beauvoir"},
  {t:"Ninguém pode construir em teu lugar as pontes que precisarás passar.", a:"Friedrich Nietzsche"},
  {t:"Há um tempo de plantar e um tempo de colher.", a:"Provérbio"},
  {t:"Os que se entregam à prática sem ciência são como navegantes sem leme.", a:"Leonardo da Vinci"},
  {t:"Águas tranquilas são as mais profundas.", a:"Provérbio"},
  {t:"A pressa é inimiga da perfeição.", a:"Provérbio"},
  {t:"Devagar se vai ao longe.", a:"Provérbio"},
  {t:"De grão em grão, a galinha enche o papo.", a:"Provérbio"},
  {t:"Quem não arrisca não petisca.", a:"Provérbio"},
  {t:"Mais vale um pássaro na mão do que dois voando.", a:"Provérbio"},
  {t:"Água mole em pedra dura, tanto bate até que fura.", a:"Provérbio"},
  {t:"Quem semeia ventos colhe tempestades.", a:"Provérbio"},
  {t:"O barato sai caro.", a:"Provérbio"},
  {t:"Quem espera sempre alcança.", a:"Provérbio"},
  {t:"O hábito não faz o monge.", a:"Provérbio"},
  {t:"Antes só do que mal acompanhado.", a:"Provérbio"},
  {t:"Cada macaco no seu galho.", a:"Provérbio"},
  {t:"A união faz a força.", a:"Provérbio"},
  {t:"Quem tudo quer tudo perde.", a:"Provérbio"},
  {t:"Em casa de ferreiro, espeto de pau.", a:"Provérbio"},
  {t:"Filho de peixe, peixinho é.", a:"Provérbio"},
  {t:"Não adianta chorar sobre o leite derramado.", a:"Provérbio"},
  {t:"O olho do dono é que engorda o gado.", a:"Provérbio"},
  {t:"Cada um colhe o que planta.", a:"Provérbio"},
  {t:"Diga-me com quem andas e te direi quem és.", a:"Provérbio"},
  {t:"A esperança é a última que morre.", a:"Provérbio"},
  {t:"Quem canta seus males espanta.", a:"Provérbio"},
  {t:"Não deixe a peteca cair.", a:"Provérbio"},
  {t:"Vamos com tudo, porque com metade ninguém vai.", a:"Anônimo"},
  {t:"O importante é não parar de questionar.", a:"Albert Einstein"},
  {t:"O fracasso é o tempero que dá sabor ao sucesso.", a:"Truman Capote"},
  {t:"Se você não está disposto a arriscar o usual, terá que se contentar com o comum.", a:"Jim Rohn"},
  {t:"Cuide do seu corpo. É o único lugar que você tem para viver.", a:"Jim Rohn"},
  {t:"Trabalhe mais em você do que no seu emprego.", a:"Jim Rohn"},
  {t:"Não deseje que fosse mais fácil; deseje que você fosse melhor.", a:"Jim Rohn"},
  {t:"Você é a média das cinco pessoas com quem passa mais tempo.", a:"Jim Rohn"},
  {t:"A disciplina pesa gramas; o arrependimento pesa toneladas.", a:"Jim Rohn"},
  {t:"O sucesso não é dele para ser tido; é dele para ser atraído por quem você se torna.", a:"Jim Rohn"},
  {t:"Lucros são melhores que salários.", a:"Jim Rohn"},
  {t:"Não comece o dia até ter ele terminado no papel.", a:"Jim Rohn"},
  {t:"A motivação é o que te faz começar. O hábito é o que te mantém.", a:"Jim Ryun"},
  {t:"Faça as coisas comuns de maneira incomum.", a:"George Washington Carver"},
  {t:"A liderança é a capacidade de transformar visão em realidade.", a:"Warren Bennis"},
  {t:"Lidere pelo exemplo.", a:"Anônimo"},
  {t:"O preço da disciplina é sempre menor que a dor do arrependimento.", a:"Anônimo"},
  {t:"O cliente não espera que você seja perfeito. Espera que você resolva quando algo der errado.", a:"Donald Porter"},
  {t:"Qualidade significa fazer certo quando ninguém está olhando.", a:"Henry Ford"},
  {t:"A satisfação do cliente é inútil; a fidelidade do cliente não tem preço.", a:"Jeffrey Gitomer"},
  {t:"Seu cliente mais insatisfeito é sua maior fonte de aprendizado.", a:"Bill Gates"},
  {t:"A vida é dura, mas você é mais.", a:"Anônimo"},
  {t:"Paciência e perseverança têm o efeito mágico de fazer as dificuldades desaparecerem.", a:"John Quincy Adams"},
  {t:"Se seus sonhos não te assustam, eles não são grandes o suficiente.", a:"Ellen Johnson Sirleaf"},
  {t:"Trabalho em equipe é o combustível que permite a pessoas comuns atingir resultados incomuns.", a:"Andrew Carnegie"},
  {t:"A força está nas diferenças, não nas semelhanças.", a:"Stephen Covey"},
  {t:"Comece com o fim em mente.", a:"Stephen Covey"},
  {t:"As coisas mais importantes nunca devem ficar à mercê das menos importantes.", a:"Stephen Covey"},
  {t:"Procure primeiro compreender, depois ser compreendido.", a:"Stephen Covey"},
  {t:"Não somos seres humanos vivendo uma experiência espiritual. Somos seres espirituais vivendo uma experiência humana.", a:"Teilhard de Chardin"},
  {t:"A vida é 10% o que acontece com você e 90% como você reage.", a:"Charles Swindoll"},
  {t:"O melhor preparo para amanhã é fazer o seu melhor hoje.", a:"H. Jackson Brown Jr."},
  {t:"Lembre-se de que as pessoas mais felizes não têm o melhor de tudo, fazem o melhor de tudo.", a:"H. Jackson Brown Jr."},
  {t:"A motivação vem de trabalhar naquilo que nos importa.", a:"Sheryl Sandberg"},
  {t:"Feito é melhor que perfeito.", a:"Sheryl Sandberg"},
  {t:"Se lhe oferecem um lugar num foguete, não pergunte qual assento. Apenas entre.", a:"Sheryl Sandberg"},
  {t:"Não tenha medo de desistir do que é bom para buscar o que é grandioso.", a:"John D. Rockefeller"},
  {t:"A melhor vingança é um sucesso enorme.", a:"Frank Sinatra"},
  {t:"O sucesso é a melhor vingança.", a:"Frank Sinatra"},
  {t:"Cada coisa a seu tempo, e tudo será bem feito.", a:"Anônimo"},
  {t:"Trabalhe enquanto eles dormem. Aprenda enquanto eles festejam.", a:"Anônimo"},
  {t:"A sorte favorece a mente preparada.", a:"Louis Pasteur"},
  {t:"Onde há vontade, há um caminho; onde há time, há vitória.", a:"Anônimo"},
  {t:"O segredo do sucesso é a constância no propósito.", a:"Benjamin Disraeli"},
  {t:"Aja como se o que você faz fizesse diferença. Faz.", a:"William James"},
  {t:"A maior descoberta é que um ser humano pode mudar sua vida mudando sua atitude.", a:"William James"},
  {t:"Nós nos tornamos aquilo que pensamos.", a:"Earl Nightingale"},
  {t:"Pessoas com metas têm sucesso porque sabem para onde estão indo.", a:"Earl Nightingale"},
  {t:"Não pare quando estiver cansado. Pare quando terminar.", a:"Anônimo"},
  {t:"Você não precisa ser grande para começar, mas precisa começar para ser grande.", a:"Zig Ziglar"},
  {t:"Faltam pessoas que aproveitam as oportunidades, não oportunidades.", a:"Zig Ziglar"},
  {t:"Você pode ter tudo na vida se ajudar outras pessoas a conseguirem o que querem.", a:"Zig Ziglar"},
  {t:"As pessoas costumam dizer que motivação não dura. Bem, banho também não; por isso recomenda-se diariamente.", a:"Zig Ziglar"},
  {t:"Lembre-se de que o fracasso é um evento, não uma pessoa.", a:"Zig Ziglar"},
  {t:"A repetição é a mãe da habilidade.", a:"Tony Robbins"},
  {t:"Onde foco vai, energia flui.", a:"Tony Robbins"},
  {t:"A qualidade da sua vida é a qualidade das suas perguntas.", a:"Tony Robbins"},
  {t:"Não é a falta de recursos, mas a falta de engenhosidade.", a:"Tony Robbins"},
  {t:"Pequenas mudanças diárias levam a resultados extraordinários.", a:"Anônimo"},
  {t:"Você não sobe a montanha de uma vez; sobe um passo de cada vez.", a:"Anônimo"},
  {t:"A excelência é fazer coisas comuns extraordinariamente bem.", a:"John Gardner"},
  {t:"O trabalho duro vence o talento quando o talento não trabalha duro.", a:"Tim Notke"},
  {t:"Disciplina é fazer o que precisa ser feito, mesmo sem vontade.", a:"Anônimo"},
  {t:"Não tenha medo de ir devagar; tenha medo de ficar parado.", a:"Provérbio chinês"},
  {t:"Quem planta tâmaras não colhe tâmaras, mas planta mesmo assim.", a:"Provérbio árabe"},
  {t:"A melhor hora de plantar uma árvore foi há 20 anos. A segunda melhor é agora.", a:"Provérbio chinês"},
  {t:"Cair é permitido. Levantar é obrigatório.", a:"Provérbio russo"},
  {t:"Um bom marinheiro se faz em mar revolto.", a:"Provérbio"},
  {t:"A maré sobe para todos os barcos.", a:"Provérbio"},
  {t:"Quem semeia com lágrimas colherá com alegria.", a:"Salmos"},
  {t:"O ferro afia o ferro; um homem afia o outro.", a:"Provérbios"},
  {t:"Olho por olho, e o mundo acabará cego.", a:"Mahatma Gandhi"},
  {t:"Seja a mudança que você quer ver no mundo.", a:"Mahatma Gandhi"},
  {t:"A força não vem da capacidade física, mas de uma vontade indomável.", a:"Mahatma Gandhi"},
  {t:"Viva como se fosse morrer amanhã. Aprenda como se fosse viver para sempre.", a:"Mahatma Gandhi"},
  {t:"O futuro depende daquilo que fazemos no presente.", a:"Mahatma Gandhi"},
  {t:"A felicidade é quando o que você pensa, diz e faz estão em harmonia.", a:"Mahatma Gandhi"},
  {t:"Primeiro eles te ignoram, depois riem de você, depois lutam contra você, então você vence.", a:"Mahatma Gandhi"},
  {t:"Em meio ao inverno, descobri que havia em mim um verão invencível.", a:"Albert Camus"},
  {t:"A verdadeira generosidade para com o futuro consiste em dar tudo ao presente.", a:"Albert Camus"},
  {t:"Não caminhe atrás de mim, posso não liderar. Caminhe ao meu lado e seja meu amigo.", a:"Albert Camus"},
  {t:"A liberdade não é nada além de uma chance de ser melhor.", a:"Albert Camus"},
  {t:"O óbvio nem sempre é verdadeiro.", a:"Anônimo"},
  {t:"Ame a vida que você vive. Viva a vida que você ama.", a:"Bob Marley"},
  {t:"Você nunca sabe o quão forte é até que ser forte seja a única opção.", a:"Bob Marley"},
  {t:"Abra os olhos, olhe para dentro. Você está satisfeito com a vida que vive?", a:"Bob Marley"},
  {t:"A grandeza de um homem não está em quanta riqueza ele adquire.", a:"Bob Marley"},
  {t:"Uma boa cabeça e um bom coração são sempre uma combinação formidável.", a:"Nelson Mandela"},
  {t:"Que possamos ser sempre maiores que nossos medos.", a:"Anônimo"},
  {t:"Não existe atalho para nenhum lugar que valha a pena ir.", a:"Beverly Sills"},
  {t:"A vida é curta, a arte é longa.", a:"Hipócrates"},
  {t:"Primeiro, não cause dano.", a:"Hipócrates"},
  {t:"Que o alimento seja teu remédio.", a:"Hipócrates"},
  {t:"Tudo flui; nada permanece.", a:"Heráclito"},
  {t:"Ninguém entra duas vezes no mesmo rio.", a:"Heráclito"},
  {t:"O caráter de um homem é o seu destino.", a:"Heráclito"},
  {t:"A maior riqueza é viver contente com pouco.", a:"Platão"},
  {t:"O início é a parte mais importante do trabalho.", a:"Platão"},
  {t:"A necessidade é a mãe da invenção.", a:"Platão"},
  {t:"A coragem é saber o que não temer.", a:"Platão"},
  {t:"Sábio é aquele que sabe o que não sabe.", a:"Lao-Tsé"},
  {t:"Quem conhece os outros é inteligente; quem conhece a si mesmo é iluminado.", a:"Lao-Tsé"},
  {t:"Dominar os outros é força; dominar a si mesmo é o verdadeiro poder.", a:"Lao-Tsé"},
  {t:"Quando eu solto o que sou, me torno o que poderia ser.", a:"Lao-Tsé"},
  {t:"Faça as coisas difíceis enquanto são fáceis e as grandes enquanto são pequenas.", a:"Lao-Tsé"},
  {t:"A natureza não tem pressa, e ainda assim tudo se realiza.", a:"Lao-Tsé"},
  {t:"Aja sem esperar nada e nada lhe faltará.", a:"Lao-Tsé"},
  {t:"Não há nada mais constante do que a mudança.", a:"Heráclito"},
  {t:"O homem prudente não despreza as pequenas coisas.", a:"Provérbio"},
  {t:"Tenha em mente que o seu próprio resolvido sucesso é mais importante.", a:"Abraham Lincoln"},
  {t:"A melhor maneira de prever o seu futuro é criá-lo.", a:"Abraham Lincoln"},
  {t:"Eu caminho devagar, mas nunca para trás.", a:"Abraham Lincoln"},
  {t:"Dê-me seis horas para cortar uma árvore e passarei as primeiras quatro afiando o machado.", a:"Abraham Lincoln"},
  {t:"Quase todos podem suportar adversidades, mas se quer testar o caráter de um homem, dê-lhe poder.", a:"Abraham Lincoln"},
  {t:"As coisas podem vir para aqueles que esperam, mas só as coisas deixadas por aqueles que correm atrás.", a:"Abraham Lincoln"},
  {t:"Não importa quão longa seja a noite, o amanhecer chegará.", a:"Provérbio africano"},
  {t:"Se quer ir rápido, vá sozinho. Se quer ir longe, vá acompanhado.", a:"Provérbio africano"},
  {t:"A chuva não cai num telhado só.", a:"Provérbio africano"},
  {t:"Uma só pulseira não tilinta.", a:"Provérbio africano"},
  {t:"Sabedoria é como o baobá; ninguém consegue abraçá-la sozinho.", a:"Provérbio africano"},
  {t:"O conhecimento é como um jardim: se não for cultivado, não pode ser colhido.", a:"Provérbio africano"},
  {t:"Mãos que ajudam são mais sagradas que lábios que rezam.", a:"Madre Teresa de Calcutá"},
  {t:"Não podemos fazer grandes coisas, apenas pequenas coisas com grande amor.", a:"Madre Teresa de Calcutá"},
  {t:"A paz começa com um sorriso.", a:"Madre Teresa de Calcutá"},
  {t:"Faça o que está fazendo bem feito.", a:"Madre Teresa de Calcutá"},
  {t:"Se você julga as pessoas, não tem tempo de amá-las.", a:"Madre Teresa de Calcutá"},
  {t:"Bondade nas palavras gera confiança.", a:"Lao-Tsé"},
  {t:"O entusiasmo é a eletricidade da vida.", a:"Gordon Parks"},
  {t:"Faça o trabalho com amor e verá milagres.", a:"Anônimo"},
  {t:"Disciplina é liberdade.", a:"Jocko Willink"},
  {t:"Quando as coisas dão errado, não vá com elas.", a:"Elvis Presley"},
  {t:"Acredito que cada um de nós tem um chamado.", a:"Oprah Winfrey"},
  {t:"A maior aventura que você pode ter é viver a vida dos seus sonhos.", a:"Oprah Winfrey"},
  {t:"Faça o melhor que puder, e quando souber mais, faça melhor.", a:"Oprah Winfrey"},
  {t:"A paixão é energia. Sinta a força que vem de focar no que te entusiasma.", a:"Oprah Winfrey"},
  {t:"Rodeie-se apenas de pessoas que vão te elevar.", a:"Oprah Winfrey"},
  {t:"A gratidão transforma o que temos em suficiente.", a:"Anônimo"},
  {t:"Sorria, respire e vá devagar.", a:"Thich Nhat Hanh"},
  {t:"A paz vem de dentro. Não a procure fora.", a:"Buda"},
  {t:"Cada experiência, por mais ruim que pareça, é um tesouro.", a:"Og Mandino"},
  {t:"Vou perseverar até ter sucesso.", a:"Og Mandino"},
  {t:"O verdadeiro fracasso é não tentar.", a:"Og Mandino"},
  {t:"Use o dia de hoje sabiamente, pois ele nunca voltará.", a:"Og Mandino"},
  {t:"O segredo está em transformar o trabalho em prazer.", a:"Anônimo"},
  {t:"Comprometa-se com o processo e os resultados virão.", a:"Anônimo"},
  {t:"A excelência é uma jornada, não um destino.", a:"Anônimo"},
  {t:"Foco no progresso, não na perfeição.", a:"Anônimo"},
  {t:"Você é mais forte do que pensa e mais capaz do que imagina.", a:"Anônimo"},
  {t:"Cada amanhecer traz uma nova oportunidade.", a:"Anônimo"},
  {t:"Acredite no processo.", a:"Anônimo"},
  {t:"A diferença entre tentar e triunfar é um pouco de garra.", a:"Marvin Phillips"},
  {t:"Nunca é tarde demais para ser quem você poderia ter sido.", a:"George Eliot"},
  {t:"A dúvida mata mais sonhos do que o fracasso jamais matará.", a:"Suzy Kassem"},
  {t:"Acredite que é possível e você verá soluções; acredite que é impossível e verá obstáculos.", a:"Wayne Dyer"},
  {t:"Mude a maneira de olhar as coisas e as coisas que você olha mudam.", a:"Wayne Dyer"},
  {t:"O que vem fácil não dura; o que dura não vem fácil.", a:"Anônimo"},
  {t:"Foque no que você pode controlar.", a:"Epiteto"},
  {t:"Não são as coisas que nos perturbam, mas o que pensamos sobre elas.", a:"Epiteto"},
  {t:"Primeiro diga a si mesmo o que você quer ser; depois faça o que tem de fazer.", a:"Epiteto"},
  {t:"Nenhum homem é livre se não for senhor de si.", a:"Epiteto"},
  {t:"A riqueza consiste não em ter grandes posses, mas em ter poucas necessidades.", a:"Epiteto"},
  {t:"Não explique sua filosofia. Incorpore-a.", a:"Epiteto"},
  {t:"Você se torna o que dá atenção.", a:"Epiteto"},
  {t:"A felicidade e a liberdade começam com a compreensão de um princípio: algumas coisas estão sob nosso controle.", a:"Epiteto"},
  {t:"O obstáculo é o caminho.", a:"Marco Aurélio"},
  {t:"Você tem poder sobre a sua mente, não sobre os eventos externos. Perceba isso e encontrará força.", a:"Marco Aurélio"},
  {t:"A felicidade da sua vida depende da qualidade dos seus pensamentos.", a:"Marco Aurélio"},
  {t:"Desperdiçar tempo não é mais grave do que desperdiçar atenção.", a:"Marco Aurélio"},
  {t:"A melhor vingança é não ser como quem cometeu a injustiça.", a:"Marco Aurélio"},
  {t:"O que impede a ação avança a ação. O que está no caminho torna-se o caminho.", a:"Marco Aurélio"},
  {t:"Confine-se ao presente.", a:"Marco Aurélio"},
  {t:"Não perca mais tempo discutindo como deve ser um bom homem. Seja um.", a:"Marco Aurélio"},
  {t:"A coisa mais bela que podemos experimentar é o mistério.", a:"Albert Einstein"},
  {t:"Aprenda com o ontem, viva o hoje, tenha esperança no amanhã.", a:"Albert Einstein"},
  {t:"Não temos o direito de consumir felicidade sem produzi-la.", a:"George Bernard Shaw"},
  {t:"O progresso é impossível sem mudança.", a:"George Bernard Shaw"},
  {t:"A vida não é sobre se encontrar; é sobre se criar.", a:"George Bernard Shaw"},
  {t:"As pessoas razoáveis se adaptam ao mundo; as não razoáveis insistem em adaptar o mundo a si.", a:"George Bernard Shaw"},
  {t:"Use o seu sorriso para mudar o mundo, não deixe o mundo mudar o seu sorriso.", a:"Anônimo"},
  {t:"Quando uma porta se fecha, outra se abre.", a:"Alexander Graham Bell"},
  {t:"Antes de tudo, preparação é a chave do sucesso.", a:"Alexander Graham Bell"},
  {t:"Concentre todos os seus pensamentos na tarefa em mãos.", a:"Alexander Graham Bell"},
  {t:"Gênio é 1% inspiração e 99% transpiração.", a:"Thomas Edison"},
  {t:"Não falhei. Apenas descobri 10 mil maneiras que não funcionam.", a:"Thomas Edison"},
  {t:"Nossa maior fraqueza está em desistir. O caminho mais certo para vencer é tentar mais uma vez.", a:"Thomas Edison"},
  {t:"A oportunidade é perdida pela maioria porque vem vestida de macacão e parece trabalho.", a:"Thomas Edison"},
  {t:"O valor de uma ideia está em colocá-la em prática.", a:"Thomas Edison"},
  {t:"Eu nunca trabalhei um dia na vida. Tudo era diversão.", a:"Thomas Edison"},
  {t:"Tudo aquilo que a mente humana pode conceber e acreditar, ela pode alcançar.", a:"Napoleon Hill"},
  {t:"O ponto de partida de toda conquista é o desejo.", a:"Napoleon Hill"},
  {t:"A força do pensamento é a luz do conhecimento.", a:"Napoleon Hill"},
  {t:"Não espere. O tempo nunca será o ideal.", a:"Napoleon Hill"},
  {t:"As metas são sonhos com prazo.", a:"Napoleon Hill"},
  {t:"Toda adversidade traz consigo a semente de um benefício equivalente.", a:"Napoleon Hill"},
  {t:"A paciência, a persistência e a transpiração formam uma combinação imbatível para o sucesso.", a:"Napoleon Hill"},
  {t:"A planta mais alta começou como uma semente.", a:"Anônimo"},
  {t:"Coragem é graça sob pressão.", a:"Ernest Hemingway"},
  {t:"O melhor jeito de descobrir se você pode confiar em alguém é confiar.", a:"Ernest Hemingway"},
  {t:"Nunca confunda movimento com ação.", a:"Ernest Hemingway"},
  {t:"Hoje é sempre o melhor dia para recomeçar.", a:"Anônimo"},
  {t:"Comprometimento é continuar muito depois que o clima em que você prometeu já passou.", a:"Anônimo"},
  {t:"Faça acontecer, não espere acontecer.", a:"Anônimo"},
  {t:"A persistência transforma o fracasso em realizações extraordinárias.", a:"Matt Biondi"},
  {t:"Os campeões continuam jogando até acertarem.", a:"Billie Jean King"},
  {t:"Pressão é privilégio.", a:"Billie Jean King"},
  {t:"Campeões não nascem prontos; são forjados.", a:"Anônimo"},
  {t:"O sucesso não é final, o fracasso não é fatal: o que conta é a coragem de continuar.", a:"Winston Churchill"},
  {t:"A vitória pertence ao mais perseverante.", a:"Napoleão Bonaparte"},
  {t:"A palavra impossível não está no meu dicionário.", a:"Napoleão Bonaparte"},
  {t:"Um líder é um negociante de esperança.", a:"Napoleão Bonaparte"},
  {t:"Quem teme perder já está vencido.", a:"Provérbio"},
  {t:"Capacidade é o que você é capaz de fazer; motivação determina o que você faz; atitude determina o quão bem você faz.", a:"Lou Holtz"},
  {t:"A vida é 10% o que acontece e 90% como você responde a isso.", a:"Lou Holtz"},
  {t:"Não é o que acontece com você, mas como você reage que importa.", a:"Epiteto"},
  {t:"A mente é o seu instrumento. Aprenda a ser seu mestre, não seu escravo.", a:"Remez Sasson"},
  {t:"Plante hoje a árvore sob cuja sombra você não vai se sentar.", a:"Provérbio"},
  {t:"O que você planta agora, colherá depois.", a:"Og Mandino"},
  {t:"A excelência não é uma habilidade; é uma atitude.", a:"Ralph Marston"},
  {t:"Sua única limitação é aquela que você define em sua própria mente.", a:"Napoleon Hill"},
  {t:"O bom é inimigo do ótimo.", a:"Jim Collins"},
  {t:"Grande visão sem grandes pessoas é irrelevante.", a:"Jim Collins"},
  {t:"Primeiro quem, depois o quê.", a:"Jim Collins"},
  {t:"A boa sorte é o resíduo do planejamento.", a:"Branch Rickey"},
  {t:"A disciplina é o que transforma sonhos em realidade.", a:"Anônimo"},
  {t:"A consistência é mais importante que a intensidade.", a:"Anônimo"},
  {t:"Pequenas vitórias diárias constroem grandes resultados.", a:"Anônimo"},
  {t:"Você não precisa ver toda a escada; apenas dê o primeiro passo.", a:"Martin Luther King Jr."},
  {t:"Se não puder voar, corra. Se não puder correr, ande. Mas continue se movendo.", a:"Martin Luther King Jr."},
  {t:"A injustiça em qualquer lugar é uma ameaça à justiça em todo lugar.", a:"Martin Luther King Jr."},
  {t:"A verdadeira medida de um homem é onde ele se posiciona em momentos de desafio.", a:"Martin Luther King Jr."},
  {t:"Fé é dar o primeiro passo mesmo quando você não vê toda a escada.", a:"Martin Luther King Jr."},
  {t:"Tudo o que é feito com amor é bem feito.", a:"Vincent van Gogh"},
  {t:"Grandes coisas são feitas de uma série de pequenas coisas reunidas.", a:"Vincent van Gogh"},
  {t:"Eu sonho minha pintura e depois pinto meu sonho.", a:"Vincent van Gogh"},
  {t:"O que seria a vida se não tivéssemos coragem de tentar algo novo?", a:"Vincent van Gogh"},
  {t:"Não há nada de artístico em ser pobre; há dignidade em ser trabalhador.", a:"Anônimo"},
  {t:"Trabalho duro supera o talento quando o talento não trabalha.", a:"Kevin Durant"},
  {t:"Você sente a dor da disciplina ou a dor do arrependimento.", a:"Anônimo"},
  {t:"O sucesso é alugado, e o aluguel vence todo dia.", a:"J. J. Watt"},
  {t:"Não importa quão bom você seja, sempre há espaço para melhorar.", a:"Anônimo"},
  {t:"O esforço de hoje é a colheita de amanhã.", a:"Anônimo"},
  {t:"Aja com propósito e o resultado seguirá.", a:"Anônimo"},
  {t:"Foco e fé movem montanhas.", a:"Anônimo"},
  {t:"Não pare até se orgulhar.", a:"Anônimo"},
  {t:"A jornada de melhoria nunca termina.", a:"Anônimo"},
  {t:"Faça do esforço o seu padrão.", a:"Anônimo"},
  {t:"Vença a preguiça com um único passo.", a:"Anônimo"},
  {t:"Comece pequeno, sonhe grande.", a:"Anônimo"},
  {t:"O suor de hoje é o sorriso de amanhã.", a:"Anônimo"},
  {t:"Grandes resultados exigem grande ambição.", a:"Heráclito"},
  {t:"A dúvida é cara; a ação é valiosa.", a:"Anônimo"},
  {t:"Você nunca falha até parar de tentar.", a:"Albert Einstein"},
  {t:"Quem nunca cometeu um erro nunca tentou nada novo.", a:"Albert Einstein"},
  {t:"O essencial é invisível aos olhos.", a:"Antoine de Saint-Exupéry"},
  {t:"O futuro não precisa ser previsto, precisa ser permitido.", a:"Antoine de Saint-Exupéry"},
  {t:"Uma meta sem um plano não passa de um desejo.", a:"Antoine de Saint-Exupéry"},
  {t:"Se quer construir um barco, desperte nos homens o desejo pelo mar.", a:"Antoine de Saint-Exupéry"},
  {t:"A perfeição é alcançada não quando não há nada a acrescentar, mas quando não há nada a retirar.", a:"Antoine de Saint-Exupéry"},
  {t:"Cada dia, em todos os aspectos, estou melhorando cada vez mais.", a:"Émile Coué"},
  {t:"Tenha paciência com tudo que está sem solução em seu coração.", a:"Rainer Maria Rilke"},
  {t:"Deixe tudo acontecer com você: a beleza e o terror. Continue em frente.", a:"Rainer Maria Rilke"},
  {t:"A única jornada é a que se faz para dentro.", a:"Rainer Maria Rilke"},
  {t:"A vida só pode ser compreendida olhando-se para trás, mas só pode ser vivida olhando-se para frente.", a:"Søren Kierkegaard"},
  {t:"Atrever-se é perder o equilíbrio momentaneamente; não se atrever é perder-se a si mesmo.", a:"Søren Kierkegaard"},
  {t:"A pior mentira é aquela que contamos a nós mesmos.", a:"Anônimo"},
  {t:"Acredite no seu potencial mesmo quando ninguém mais acreditar.", a:"Anônimo"},
  {t:"O trabalho bem feito traz uma satisfação que nada substitui.", a:"Anônimo"},
  {t:"Faça hoje algo de que seu futuro eu se orgulhe.", a:"Anônimo"},
  {t:"Você é capaz de coisas incríveis.", a:"Anônimo"},
  {t:"Transforme cada obstáculo em um degrau.", a:"Anônimo"},
  {t:"O esforço nunca é em vão.", a:"Anônimo"},
  {t:"Mantenha a calma e siga em frente.", a:"Provérbio britânico"},
  {t:"Quem persiste sempre alcança.", a:"Provérbio"},
  {t:"Cada conquista começa com a decisão de tentar.", a:"Gail Devers"},
  {t:"Quando você fala, repete o que já sabe. Quando ouve, pode aprender algo novo.", a:"Dalai Lama"},
  {t:"O amor e a compaixão são necessidades, não luxos.", a:"Dalai Lama"},
  {t:"Julgue seu sucesso pelo que teve de abrir mão para alcançá-lo.", a:"Dalai Lama"},
  {t:"Dê às pessoas mais do que elas esperam e faça isso com alegria.", a:"Dalai Lama"},
  {t:"A regra de ouro: trate os outros como gostaria de ser tratado.", a:"Provérbio"},
  {t:"Cooperação é fazer juntos o que ninguém faria sozinho.", a:"Anônimo"},
  {t:"Um time unido é imbatível.", a:"Anônimo"},
  {t:"O todo é mais forte quando cada parte faz a sua.", a:"Anônimo"},
  {t:"Sozinhos fazemos pouco; juntos fazemos muito.", a:"Helen Keller"},
  {t:"O otimismo é a fé que leva à realização.", a:"Helen Keller"},
  {t:"A vida é uma aventura ousada ou não é nada.", a:"Helen Keller"},
  {t:"O melhor e mais belo do mundo não pode ser visto nem tocado; deve ser sentido com o coração.", a:"Helen Keller"},
  {t:"Mantenha o rosto voltado para o sol e não verá as sombras.", a:"Helen Keller"},
  {t:"Caminhar com um amigo no escuro é melhor do que caminhar sozinho na luz.", a:"Helen Keller"},
  {t:"O caráter não se desenvolve na tranquilidade, mas na provação.", a:"Helen Keller"},
  {t:"Tudo posso, nada me impede.", a:"Anônimo"},
  {t:"Quando você melhora um pouquinho a cada dia, coisas grandes acontecem.", a:"John Wooden"},
  {t:"Não se preocupe em ser melhor que os outros; seja melhor que você foi ontem.", a:"Provérbio"},
  {t:"O sucesso é a paz de espírito de saber que você fez o seu melhor.", a:"John Wooden"},
  {t:"Coisas grandes não são feitas por impulso, mas por uma série de pequenas coisas reunidas.", a:"Vincent van Gogh"},
  {t:"A maior glória não é nunca cair, mas levantar cada vez que caímos.", a:"Confúcio"},
  {t:"Aja como se fosse impossível falhar.", a:"Winston Churchill"},
  {t:"Não há vento favorável para quem não sabe aonde vai.", a:"Sêneca"},
  {t:"Não é porque as coisas são difíceis que não ousamos; é porque não ousamos que são difíceis.", a:"Sêneca"},
  {t:"Enquanto esperamos pela vida, a vida passa.", a:"Sêneca"},
  {t:"A sorte é o que acontece quando a preparação encontra a oportunidade.", a:"Sêneca"},
  {t:"Todo novo começo vem do fim de outro começo.", a:"Sêneca"},
  {t:"Não é que tenhamos pouco tempo, é que perdemos muito dele.", a:"Sêneca"},
  {t:"Às vezes até viver é um ato de coragem.", a:"Sêneca"},
  {t:"Dificuldades fortalecem a mente, assim como o trabalho fortalece o corpo.", a:"Sêneca"},
  {t:"Comece imediatamente a viver e conte cada dia como uma vida completa.", a:"Sêneca"},
  {t:"Não há nada que o tempo e o trabalho não resolvam.", a:"Provérbio"},
  {t:"A pressa traz arrependimento; a calma traz segurança.", a:"Provérbio"},
  {t:"Mãos à obra: o trabalho é a melhor oração.", a:"Anônimo"},
  {t:"Faça o que é certo, mesmo quando ninguém está vendo.", a:"C. S. Lewis"},
  {t:"Você nunca é velho demais para definir outra meta ou sonhar um novo sonho.", a:"C. S. Lewis"},
  {t:"Dificuldades preparam pessoas comuns para destinos extraordinários.", a:"C. S. Lewis"},
  {t:"O futuro recompensa aqueles que continuam avançando.", a:"Barack Obama"},
  {t:"A mudança não virá se esperarmos por outra pessoa. Nós somos a mudança que buscamos.", a:"Barack Obama"},
  {t:"Não deixe que ninguém te diga que você não pode fazer algo.", a:"Will Smith"},
  {t:"O talento que você tem naturalmente, mas a habilidade vem com horas batendo no seu ofício.", a:"Will Smith"},
  {t:"Se você não corre atrás do que quer, nunca vai ter.", a:"Anônimo"},
  {t:"Quem não tenta, nem sabe o que perde.", a:"Anônimo"},
  {t:"O medo é uma reação; a coragem é uma decisão.", a:"Winston Churchill"},
  {t:"O fracasso é apenas a oportunidade de começar de novo de forma mais inteligente.", a:"Henry Ford"},
  {t:"Mire na lua. Mesmo que erre, você cairá entre as estrelas.", a:"Norman Vincent Peale"},
  {t:"Mude seus pensamentos e você muda o seu mundo.", a:"Norman Vincent Peale"},
  {t:"Acredite que algo maravilhoso pode acontecer.", a:"Norman Vincent Peale"},
  {t:"Pessoas comuns que fazem esforços extraordinários alcançam resultados extraordinários.", a:"Anônimo"},
  {t:"A repetição leva à maestria.", a:"Anônimo"},
  {t:"Vá além do esperado, sempre.", a:"Anônimo"},
  {t:"Atenção aos detalhes faz a diferença entre o bom e o excelente.", a:"Anônimo"},
  {t:"Fazer bem feito da primeira vez economiza tempo e energia.", a:"Anônimo"},
  {t:"Capriche: o seu trabalho é a sua assinatura.", a:"Anônimo"},
  {t:"Orgulhe-se do que você entrega.", a:"Anônimo"},
  {t:"Um trabalho bem feito fala por você.", a:"Anônimo"},
  {t:"Quem cuida dos detalhes domina o todo.", a:"Anônimo"},
  {t:"A reputação se constrói uma entrega de cada vez.", a:"Anônimo"},
  {t:"Excelência é o resultado de se importar de verdade.", a:"Anônimo"},
  {t:"Não meça esforços para fazer o seu melhor.", a:"Anônimo"},
  {t:"Os detalhes não são detalhes; eles fazem o produto.", a:"Charles Eames"},
  {t:"Faça simples, mas significativo.", a:"Don Draper"},
  {t:"A simplicidade é a sofisticação suprema.", a:"Leonardo da Vinci"},
  {t:"Construa hoje a versão de você que você quer ser amanhã.", a:"Anônimo"},
  {t:"O sucesso ama a preparação.", a:"Anônimo"},
  {t:"Cada cliente satisfeito é uma vitória da equipe.", a:"Anônimo"},
  {t:"O cuidado com o cliente começa com o cuidado no trabalho.", a:"Anônimo"},
  {t:"Faça o cliente sorrir e ele voltará.", a:"Anônimo"},
  {t:"A qualidade é lembrada muito depois que o preço é esquecido.", a:"Aldo Gucci"},
  {t:"Bom trabalho gera bom nome.", a:"Provérbio"},
  {t:"O profissionalismo está nos detalhes.", a:"Anônimo"},
  {t:"Compromisso é entregar o combinado, sempre.", a:"Anônimo"},
  {t:"Respeito se conquista com atitude e entrega.", a:"Anônimo"},
  {t:"A pontualidade é a cortesia dos campeões.", a:"Provérbio"},
  {t:"Organização hoje é tranquilidade amanhã.", a:"Anônimo"},
  {t:"Planejar é trazer o futuro para o presente.", a:"Alan Lakein"},
  {t:"Falhar em planejar é planejar para falhar.", a:"Benjamin Franklin"},
  {t:"A clareza precede o sucesso.", a:"Robin Sharma"},
  {t:"Líderes inspiram pelo exemplo, não pela ordem.", a:"Robin Sharma"},
  {t:"As coisas comuns feitas com consistência produzem resultados extraordinários.", a:"Robin Sharma"},
  {t:"Comece o dia vencendo a si mesmo.", a:"Robin Sharma"},
  {t:"Quanto melhor você cuida do seu trabalho, melhor seu trabalho cuida de você.", a:"Anônimo"},
  {t:"A atitude é uma escolha diária.", a:"Anônimo"},
  {t:"O esforço extra é o que separa o comum do extraordinário.", a:"Jimmy Johnson"},
  {t:"Não busque ser perfeito; busque ser melhor.", a:"Anônimo"},
  {t:"A vitória pertence a quem se prepara.", a:"Sun Tzu"},
  {t:"Oportunidades se multiplicam quando são aproveitadas.", a:"Sun Tzu"},
  {t:"No meio do caos, há também oportunidade.", a:"Sun Tzu"},
  {t:"Conheça o inimigo e a si mesmo e vencerá cem batalhas.", a:"Sun Tzu"},
  {t:"A estratégia sem tática é o caminho mais lento para a vitória.", a:"Sun Tzu"},
  {t:"O bom guerreiro vence primeiro e depois vai à guerra.", a:"Sun Tzu"},
  {t:"Planeje o difícil enquanto é fácil.", a:"Sun Tzu"},
  {t:"A maior vitória é aquela que dispensa a batalha.", a:"Sun Tzu"},
  {t:"Disciplina e foco são meio caminho andado.", a:"Anônimo"},
  {t:"Não há crescimento na zona de conforto, e não há conforto na zona de crescimento.", a:"Anônimo"},
  {t:"Faça do desafio o seu combustível.", a:"Anônimo"},
  {t:"O sucesso é a recompensa da persistência.", a:"Anônimo"},
  {t:"Acredite, trabalhe e conquiste.", a:"Anônimo"},
  {t:"Pense grande, comece agora.", a:"Anônimo"},
  {t:"A melhor versão de você está a um esforço de distância.", a:"Anônimo"},
  {t:"Hoje é um ótimo dia para fazer um ótimo trabalho.", a:"Anônimo"},
  {t:"Vamos juntos mais longe.", a:"Anônimo"},
  {t:"O nosso melhor é o nosso padrão.", a:"Anônimo"},
  {t:"Capriche, que o resultado aparece.", a:"Anônimo"},
  {t:"Um passo de cada vez, mas sempre para frente.", a:"Anônimo"},
  {t:"Quem ama o que faz, faz bem feito.", a:"Anônimo"},
  {t:"O orgulho do dever cumprido não tem preço.", a:"Anônimo"},
  {t:"Trabalho em equipe transforma o impossível em feito.", a:"Anônimo"},
  {t:"O sucesso de hoje foi construído pelo esforço de ontem.", a:"Anônimo"},
  {t:"Faça acontecer e celebre cada conquista.", a:"Anônimo"}
];

function fraseAleatoria() {
  return FRASES[Math.floor(Math.random() * FRASES.length)];
}

// Frase estável durante o dia (muda à meia-noite).
function fraseDoDia() {
  const d = new Date();
  const seed = d.getFullYear() * 1000 + (d.getMonth() * 31 + d.getDate());
  return FRASES[seed % FRASES.length];
}

function fraseFmt(f) {
  return f ? `“${f.t}” — ${f.a}` : '';
}

// ── UI compartilhada (barra de frase + celebração) ────────────────────
// Usada por app.js (PCP/gestão) e equipe.js (rua). Tudo opcional: se os
// elementos não existirem na página, as funções simplesmente não fazem nada.

let _fraseTimer = null;
function iniciarFraseBar(intervaloMs) {
  const bar = document.getElementById('frase-bar');
  if (!bar) return;
  function pintar(f) {
    bar.innerHTML =
      '<span class="frase-ico">💬</span>' +
      '<span><span class="frase-txt">' + _esc(f.t) + '</span> ' +
      '<span class="frase-aut">— ' + _esc(f.a) + '</span></span>';
  }
  pintar(fraseDoDia());
  bar.onclick = function () {
    bar.classList.add('fade');
    setTimeout(function () { pintar(fraseAleatoria()); bar.classList.remove('fade'); }, 400);
  };
  if (_fraseTimer) clearInterval(_fraseTimer);
  _fraseTimer = setInterval(function () {
    bar.classList.add('fade');
    setTimeout(function () { pintar(fraseAleatoria()); bar.classList.remove('fade'); }, 400);
  }, intervaloMs || 30000);
}

// Classe de cor conforme a nota (0–10).
function _classeNota(n) {
  if (n >= 8) return 'bom';
  if (n >= 5) return 'medio';
  return 'baixo';
}

// opts = { emoji, titulo, frase:{t,a}, notas:[{nome,nota}], onClose }
function mostrarCelebracao(opts) {
  opts = opts || {};
  const ov = document.getElementById('celebra-overlay');
  const box = document.getElementById('celebra-box');
  if (!ov || !box) return;
  const f = opts.frase || fraseAleatoria();

  let notasHtml = '';
  if (opts.notas && opts.notas.length) {
    notasHtml = '<div class="cel-notas">' + opts.notas.map(function (p) {
      const n = Math.round((p.nota || 0) * 10); // nota 0–10 → % 0–100
      const cls = _classeNota(p.nota || 0);
      return '<div class="cel-nota-row">' +
        '<span class="cel-nota-nome">' + _esc(p.nome) + '</span>' +
        '<span class="cel-nota-val ' + cls + '">' + n + '%</span>' +
        '</div>';
    }).join('') + '</div>';
  }

  box.innerHTML =
    '<div class="celebra-confetti">' + _confetti() + '</div>' +
    '<div class="cel-emoji">' + (opts.emoji || '🎉') + '</div>' +
    '<h3 class="cel-titulo">' + _esc(opts.titulo || 'Mandou bem!') + '</h3>' +
    '<div class="cel-frase">“' + _esc(f.t) + '”' +
      '<span class="cel-aut">— ' + _esc(f.a) + '</span></div>' +
    notasHtml +
    '<button class="btn-primary cel-fechar" id="cel-fechar-btn">Continuar 🚀</button>';

  ov.classList.remove('hidden');
  function fechar() {
    ov.classList.add('hidden');
    if (typeof opts.onClose === 'function') opts.onClose();
  }
  document.getElementById('cel-fechar-btn').onclick = fechar;
  ov.onclick = function (e) { if (e.target === ov) fechar(); };
}

function _confetti() {
  const cores = ['#1877f2', '#7c3aed', '#16a34a', '#d97706', '#dc2626', '#0d9488'];
  let s = '';
  for (let i = 0; i < 28; i++) {
    const left = Math.random() * 100;
    const dur = 1.4 + Math.random() * 1.6;
    const delay = Math.random() * 0.6;
    const c = cores[i % cores.length];
    s += '<span style="left:' + left.toFixed(1) + '%;background:' + c +
      ';animation-duration:' + dur.toFixed(2) + 's;animation-delay:' + delay.toFixed(2) + 's;"></span>';
  }
  return s;
}

function _esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
